-- Execute after the migration inside BEGIN / ROLLBACK. Uses only random test
-- users and a dedicated temporary hotspot; no fixture survives the transaction.
do $$
declare a uuid=gen_random_uuid();b uuid=gen_random_uuid();place uuid;city text;slug text;r uuid;state jsonb;data jsonb;ver integer;before_zone jsonb;zone text;
begin
 city='oostende';slug='community-rollback-'||a::text;
 insert into public.content_places(kind,legacy_id,city_slug,slug)values('hotspot',(select max(legacy_id)+1 from public.content_places where kind='hotspot'),city,slug)returning id into place;
 insert into public.content_place_revisions(place_id,revision_number,content,source)values(place,1,jsonb_build_object('name','Community rollback test'),'legacy_import')returning id into r;
 update public.content_places set draft_revision_id=r,published_revision_id=r where id=place;
 before_zone=(select jsonb_agg(to_jsonb(x)order by id)from public.reviews x);
 insert into auth.users(id,aud,role,email,created_at,updated_at)values(a,'authenticated','authenticated',a||'@example.invalid',now(),now()),(b,'authenticated','authenticated',b||'@example.invalid',now(),now());
 perform public.set_hotspot_like(a,city,slug,true);perform public.set_hotspot_like(a,city,slug,true);
 if(select count(*)from public.place_likes where member_id=a and place_id=place)<>1 then raise exception 'DOUBLE_LIKE';end if;
 if(public.member_hotspot_state(b,city,slug)->>'liked')::boolean then raise exception 'OTHER_MEMBER_LIKED';end if;
 perform public.set_hotspot_like(b,city,slug,true);
 if(public.public_hotspot_summaries(jsonb_build_array(jsonb_build_object('city',city,'slug',slug)))->(city||'/'||slug)->>'likes')::integer<>2 then raise exception 'LIKE_SUMMARY';end if;
 perform public.set_hotspot_like(a,city,slug,false);perform public.set_hotspot_like(a,city,slug,false);
 if exists(select 1 from public.place_likes where member_id=a and place_id=place)then raise exception 'UNLIKE';end if;
 begin perform public.set_hotspot_like(null,city,slug,true);raise exception 'GUEST_ALLOWED';exception when others then if sqlerrm<>'ACTIVE_MEMBER_REQUIRED'then raise;end if;end;
 begin perform public.set_hotspot_like(a,'missing','missing',true);raise exception 'INVALID_PLACE_ALLOWED';exception when others then if sqlerrm<>'PLACE_UNAVAILABLE'then raise;end if;end;
 state=public.submit_hotspot_review(a,city,slug,4,'Een heel fijne ervaring met onze hond.','Rollback lid',null,null,repeat('a',64));r=(state->'review'->>'id')::uuid;
 data=public.member_hotspot_export(a);
 if jsonb_array_length(data->'reviews')<>1 or data->'reviews'->0->'versions'->0->>'comment'<>'Een heel fijne ervaring met onze hond.'then raise exception 'EXPORT_MISSING_OWN_REVIEW';end if;
 if jsonb_array_length(public.member_hotspot_export(b)->'reviews')<>0 then raise exception 'EXPORT_OWNER_LEAK';end if;
 if exists(select 1 from jsonb_array_elements(public.public_hotspot_reviews(city,slug)->'reviews')e where e->>'id'=r::text)then raise exception 'PENDING_PUBLIC';end if;
 if public.member_hotspot_state(b,city,slug)->'review'<>'null'::jsonb then raise exception 'OWNER_LEAK';end if;
 begin perform public.withdraw_hotspot_review(b,city,slug,1);raise exception 'OTHER_OWNER_ALLOWED';exception when others then if sqlerrm<>'REVIEW_NOT_FOUND'then raise;end if;end;
 perform public.moderate_hotspot_review(r,1,'publish','','',null,null,null);
 data=public.public_hotspot_reviews(city,slug);
 if(data->>'count')::integer<>1 or(data->>'average')::numeric<>4 then raise exception 'PUBLISH_SUMMARY';end if;
 state=public.member_hotspot_state(a,city,slug);ver=(state->'review'->>'version')::integer;
 state=public.submit_hotspot_review(a,city,slug,2,'Een tweede ervaring, deze keer minder fijn.','Rollback lid',null,ver,repeat('a',64));
 if(public.public_hotspot_reviews(city,slug)->>'average')::numeric<>4 then raise exception 'PENDING_EDIT_CHANGED_SCORE';end if;
 begin perform public.submit_hotspot_review(a,city,slug,3,'Een stale update uit het andere tabblad.','Rollback lid',null,ver,repeat('a',64));raise exception 'NO_CONFLICT';exception when others then if sqlerrm<>'VERSION_CONFLICT'then raise;end if;end;
 ver=(state->'review'->>'version')::integer;
 perform public.moderate_hotspot_review(r,ver,'reject','Niet over de zaak','',null,null,null);
 if(public.public_hotspot_reviews(city,slug)->>'average')::numeric<>4 then raise exception 'REJECTED_EDIT_CHANGED_SCORE';end if;
 if not(public.member_hotspot_state(a,city,slug)->'review'->>'rejected_edit')::boolean then raise exception 'REJECTED_EDIT_AUTHOR_UNINFORMED';end if;
 ver=(public.member_hotspot_state(a,city,slug)->'review'->>'version')::integer;
 state=public.submit_hotspot_review(a,city,slug,3,'Onze herziene ervaring met de hond in deze zaak.','Rollback lid',null,ver,repeat('a',64));
 ver=(state->'review'->>'version')::integer;
 perform public.moderate_hotspot_review(r,ver,'publish','','',null,null,null);
 if(public.public_hotspot_reviews(city,slug)->>'count')::integer<>1 or(public.public_hotspot_reviews(city,slug)->>'average')::numeric<>3 then raise exception 'EDIT_DOUBLE_COUNT';end if;
 ver=(public.member_hotspot_state(a,city,slug)->'review'->>'version')::integer;
 begin perform public.moderate_hotspot_review(r,ver,'hide','','',null,null,null);raise exception 'NO_REASON_ALLOWED';exception when others then if sqlerrm<>'REASON_REQUIRED'then raise;end if;end;
 perform public.flag_hotspot_review(r,'privacy',repeat('c',64));
 if not exists(select 1 from jsonb_array_elements(public.admin_community_review_list('flagged','hotspot',city,place,null,'',null,null))e where e->>'id'=r::text)then raise exception 'ADMIN_FLAG_FILTER';end if;
 if jsonb_array_length(public.admin_community_review_list('all','hotspot','missing',null,null,'',null,null))<>0 then raise exception 'CITY_FILTER';end if;
 perform public.moderate_hotspot_review(r,ver,'redact','Persoonsgegevens','', 'Publieke naam','Een veilige publieke tekst over het bezoek.',null);
 if not exists(select 1 from public.hotspot_review_versions where review_id=r and comment='Onze herziene ervaring met de hond in deze zaak.')then raise exception 'ORIGINAL_LOST';end if;
 if(public.public_hotspot_reviews(city,slug)->'reviews'->0->>'comment')<>'Een veilige publieke tekst over het bezoek.'then raise exception 'REDACTION_PUBLIC';end if;
 if(public.public_hotspot_reviews(city,slug)->>'average')::numeric<>3 then raise exception 'MODERATOR_CHANGED_RATING';end if;
 begin update public.hotspot_review_versions set rating=5 where review_id=r;raise exception 'VERSION_MUTABLE';exception when others then if sqlerrm<>'REVIEW_VERSION_IMMUTABLE'then raise;end if;end;
 update public.member_profiles set status='suspended'where id=a;
 if(public.public_hotspot_reviews(city,slug)->>'count')::integer<>0 then raise exception 'SUSPENDED_PUBLIC';end if;
 begin perform public.set_hotspot_like(a,city,slug,true);raise exception 'SUSPENDED_WRITE';exception when others then if sqlerrm<>'ACTIVE_MEMBER_REQUIRED'then raise;end if;end;
 update public.member_profiles set status='active'where id=a;
 ver=(public.member_hotspot_state(a,city,slug)->'review'->>'version')::integer;
 perform public.withdraw_hotspot_review(a,city,slug,ver);
 if(public.public_hotspot_reviews(city,slug)->>'count')::integer<>0 then raise exception 'WITHDRAWN_COUNT';end if;
 begin perform public.moderate_hotspot_review(r,ver+1,'publish','','',null,null,null);raise exception 'WITHDRAWN_PUBLISHED';exception when others then if sqlerrm<>'REVIEW_WITHDRAWN'then raise;end if;end;
 perform public.set_hotspot_like(a,city,slug,true);
 delete from auth.users where id=a;
 if exists(select 1 from public.hotspot_reviews where id=r)or exists(select 1 from public.hotspot_review_versions where review_id=r)or exists(select 1 from public.hotspot_review_actions where review_id=r)or exists(select 1 from public.hotspot_review_flags where review_id=r)or exists(select 1 from public.place_likes where member_id=a)then raise exception 'ACCOUNT_DELETE_CONTENT_RETAINED';end if;
 select p.slug into zone from public.content_places p where kind='offleash'and published_revision_id is not null and archived_at is null limit 1;
 begin perform public.submit_zone_review(zone,3,'Guest','Legacy test',null,repeat('b',64));raise exception 'ZONE_GUEST_ALLOWED';exception when others then if sqlerrm<>'ACTIVE_MEMBER_REQUIRED'then raise;end if;end;
 if before_zone is distinct from(select jsonb_agg(to_jsonb(x)order by id)from public.reviews x)then raise exception 'LEGACY_CHANGED';end if;
 if has_function_privilege('anon','public.set_hotspot_like(uuid,text,text,boolean)','execute')or has_function_privilege('authenticated','public.submit_hotspot_review(uuid,text,text,integer,text,text,date,integer,text)','execute')then raise exception 'PRIVATE_RPC_EXPOSED';end if;
 if has_table_privilege('anon','public.hotspot_reviews','select')or has_table_privilege('authenticated','public.place_likes','select')then raise exception 'PRIVATE_TABLE_EXPOSED';end if;
end$$;
