project_id = "zpllibfxaizavcvztnut"

[functions.list-admin-reports]
verify_jwt = false

[functions.update-report-status]
verify_jwt = false

[functions.remove-report]
verify_jwt = false

[functions.subscribe-push]
verify_jwt = false

[functions.unsubscribe-push]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.list-push-stats]
verify_jwt = false
