// AUTO-GENERATED by generate-og-data.cjs and render-places.mjs
export default {
  "/": {
    "title": "Honden aan Zee België 2026 | Strandregels, Losloopzones & Hondvriendelijke Plekken aan de Belgische Kust",
    "description": "✓ Actuele strandregels voor honden ✓ Losloopzones en hondenweides ✓ Hondvriendelijke cafés, restaurants & hotels ✓ Alle badsteden van De Panne tot Knokke ✓ Gratis & up-to-date info 2026",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/blog": {
    "title": "Blog | HondAanZee.be — Tips, Natuur & Nieuws over Honden aan de Belgische Kust",
    "description": "Lees onze blogs over honden aan de Belgische kust: van zeehonden op het strand tot opruimacties. Nuttige info, tips en achtergronden voor elke hondenbezitter.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/hotspots": {
    "title": "Hondvriendelijke Hotspots Belgische Kust | Cafés, Restaurants, Hotels & Winkels waar Honden Welkom Zijn",
    "description": "Ontdek de beste hondvriendelijke cafés, restaurants, hotels en winkels aan de Belgische kust. Van Oostende tot Knokke - waar je hond écht welkom is. Filter op stad en type.",
    "image": "https://hondaanzee.be/og-imagefinal.webp",
    "imageAlt": "Hondvriendelijke Hotspots Belgische Kust | Cafés, Restaurants, Hotels & Winkels waar Honden Welkom Zijn"
  },
  "/diensten": {
    "title": "Dierenartsen & Dierenwinkels Belgische Kust | Praktische Diensten voor Hondenbezitters",
    "description": "Vind de beste dierenartsen en dierenwinkels aan de Belgische kust. Van Oostende tot Knokke - alle praktische diensten voor je hond op één plek. Filter op stad en type.",
    "image": "https://hondaanzee.be/og-imagefinal.webp",
    "imageAlt": "Dierenartsen & Dierenwinkels Belgische Kust | Praktische Diensten voor Hondenbezitters"
  },
  "/losloopzones": {
    "title": "Losloopzones Belgische Kust | Overzicht Hondenweides & Losloopgebieden aan Zee",
    "description": "Interactieve kaart met alle losloopzones en hondenweides aan de Belgische kust. Van De Panne tot Knokke.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/over-ons": {
    "title": "Over HondAanZee.be | Ons Verhaal & Missie – De Belgische Kust voor Hondenbezitters",
    "description": "Leer het team achter HondAanZee.be kennen. Onze missie: de meest complete, gratis gids voor hondeneigenaars aan de Belgische kust.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/steun-ons": {
    "title": "Steun HondAanZee.be | Trakteer ons op een Hondenkoekje 🐾",
    "description": "HondAanZee.be is 100% gratis. Steun ons werk en help ons de leukste plekken aan de Belgische kust te blijven delen voor hondenbezitters.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/agenda": {
    "title": "Hondvriendelijke Evenementen Belgische Kust 2026 | Agenda & Events – HondAanZee.be",
    "description": "Ontdek alle hondvriendelijke evenementen aan de Belgische kust in 2026: festivals, wandelingen en meer.",
    "image": "https://hondaanzee.be/kwispelfestival.webp"
  },
  "/kaart": {
    "title": "Interactieve Kaart Belgische Kust | Alle Hondvriendelijke Locaties op de Kaart – HondAanZee.be",
    "description": "Bekijk alle hondvriendelijke stranden, losloopzones, cafés, restaurants en dierenartsen op onze interactieve kaart.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/meldpunt": {
    "title": "Meldpunt Gif & Overlast Belgische Kust | HondAanZee.be",
    "description": "Meld verdachte stoffen, gif, afval, hondenpoep en andere overlast aan de Belgische kust.",
    "image": "https://hondaanzee.be/properstrand.webp"
  },
  "/blog/blauwalg-hond-strand-waarschuwing": {
    "title": "Doe de Water-Check: Zo Herken Je Blauwalg Voordat Je Hond Erin Zwemt Of Eruit Drinkt | HondAanZee.be Blog",
    "description": "Niets heerlijker dan je hond vrolijk het water in te zien plonzen om die opgewarmde vacht even te laten afkoelen. Maar let op voor blauwalg! Leer hier hoe je dit gevaar herkent en wat je moet doen als het misgaat.",
    "image": "https://hondaanzee.be/blauwalg.webp",
    "type": "article",
    "imageAlt": "Blauwalg in het water"
  },
  "/blog/hond-strand-warm-weer": {
    "title": "Met je hond naar zee bij warm weer: do's en don'ts voor een veilige stranddag | HondAanZee.be Blog",
    "description": "Een dagje uitwaaien op het strand met je hond is heerlijk — tot de temperaturen oplopen. Honden zweten niet zoals wij en kunnen op het open zand snel oververhit raken. Met deze do's, don'ts en een handige hitteslag-checklist hou je jullie stranddag aan de Belgische kust veilig en plezant.",
    "image": "https://hondaanzee.be/OG_schaduwv1.webp",
    "type": "article",
    "imageAlt": "Hond zoekt de schaduw op tijdens een warme dag aan de Belgische kust"
  },
  "/blog/van-trekhond-tot-strandkoning-geschiedenis-kusthonden": {
    "title": "Van trekhond tot strandkoning: de vergeten geschiedenis van kusthonden | HondAanZee.be Blog",
    "description": "Lang voor honden op het strand vooral discussie opriepen over leibanden, zones en GAS-boetes, trokken ze viskarren door het zware zand. Deze vergeten kustgeschiedenis maakt je volgende wandeling met hond plots een stuk rijker.",
    "image": "https://hondaanzee.be/hondmetkar_cover.webp",
    "type": "article",
    "imageAlt": "Breed historisch coverbeeld van een trekhond met kar aan de Belgische kust"
  },
  "/blog/zeehonden-aan-de-belgische-kust": {
    "title": "Zeehonden aan de Belgische kust: wat als je hond er eentje tegenkomt? | HondAanZee.be Blog",
    "description": "Steeds vaker rusten zeehonden uit op onze Belgische stranden. Prachtig om te zien, maar wat doe je als je hond er eentje ontdekt? In deze gids lees je alles over de twee zeehondensoorten aan onze kust, wat je moet doen bij een ontmoeting, en hoe je bijdraagt aan hun bescherming.",
    "image": "https://hondaanzee.be/zeehond.webp",
    "type": "article",
    "imageAlt": "Zeehond rustend op het Belgische strand"
  },
  "/blog/opruimacties-proper-strand-lopers": {
    "title": "Opruimacties aan de kust: samen voor een proper strand | HondAanZee.be Blog",
    "description": "Elk jaar belandt er tonnen zwerfvuil op onze Belgische stranden. Gelukkig zijn er duizenden vrijwilligers die de handen uit de mouwen steken. Ontdek hoe organisaties als de Proper Strand Lopers en Mooimakers onze kust schoon houden — en hoe jij kunt meehelpen.",
    "image": "https://hondaanzee.be/properstrand.webp",
    "type": "article",
    "imageAlt": "Vrijwilligers ruimen zwerfvuil op aan het Belgische strand"
  },
  "/blog/mooiste-bossen-belgische-kust-wandelen-met-hond": {
    "title": "De 6 mooiste bossen aan de Belgische kust om te wandelen met je hond | HondAanZee.be Blog",
    "description": "De Belgische kust is veel meer dan strand en zee. Verscholen achter de duinen liggen prachtige bossen waar je heerlijk kunt wandelen met je hond. Van het historische Calmeynbos in De Panne tot het Zeebos in Blankenberge: wij zetten de 6 mooiste kustbossen op een rij — inclusief praktische info over hondenzones, wandelroutes en bereikbaarheid.",
    "image": "https://hondaanzee.be/zeebos.webp",
    "type": "article",
    "imageAlt": "Wandelpad door het Zeebos aan de Belgische kust"
  },
  "/blog/zwemplekjes-honden-belgische-kust": {
    "title": "De leukste zwemplekjes voor je hond aan de Belgische kust (en het is niet de zee!) | HondAanZee.be Blog",
    "description": "Strand en zee zijn niet de enige plekken waar je hond kan zwemmen aan de kust. Ontdek de mooiste vijvers, kreken, kanalen en waterlopen waar je viervoeter veilig en heerlijk kan afkoelen — ver weg van golven en kwallen.",
    "image": "https://hondaanzee.be/zwemhond.webp",
    "type": "article",
    "imageAlt": "Hond zwemt vrolijk in een vijver aan de Belgische kust"
  },
  "/blog/mentale-leiband-vrijheid-met-connectie": {
    "title": "De Mentale Leiband: Vrijheid door middel van Connectie en Controle | HondAanZee.be Blog",
    "description": "De Belgische kust is voor honden een zintuiglijk paradijs. Maar achter het idyllische beeld van een loslopende hond schuilt een complexe realiteit. Ontdek de filosofie van de \"mentale leiband\" en hoe je een wandeling transformeert van controle naar vertrouwen.",
    "image": "https://hondaanzee.be/OG_verantwoordelijklos.webp",
    "type": "article",
    "imageAlt": "Hond loopt los aan zee met mentale connectie - VZW Verantwoord Los"
  },
  "/blog/spiegel-aan-de-leiband-hondenpsychologie-guillaume-dervaux": {
    "title": "De Spiegel aan de Leiband: Waarom Echte Hondenliefde Begint in de Rust | HondAanZee.be Blog",
    "description": "We trainen commando's, kopen speeltjes en overladen onze honden met enthousiasme. Maar wat als echte hondenliefde juist in stilte en rust begint? Ontdek de 4C-methode en een verfrissende visie over de band tussen mens en hond.",
    "image": "https://hondaanzee.be/OG_brunosamlulu.webp",
    "type": "article",
    "imageAlt": "Bruno, Sam en Lulu — de viervoeters achter de hondenpsychologie van Guillaume Dervaux"
  },
  "/goed-om-te-weten": {
    "title": "Goed om te weten | Honden aan de Belgische kust",
    "description": "Praktische informatie over wandelen, gezondheid en veilig op pad gaan met je hond aan de Belgische kust.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/zaak-aanmelden": {
    "title": "Zaak aanmelden | HondAanZee.be",
    "description": "Meld je hondvriendelijke zaak aan voor vermelding op HondAanZee.be.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/privacy": {
    "title": "Privacybeleid | HondAanZee.be",
    "description": "Lees hoe HondAanZee.be omgaat met privacy en anonieme bezoekersstatistieken.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/algemene-voorwaarden": {
    "title": "Algemene voorwaarden | HondAanZee.be",
    "description": "De algemene voorwaarden voor het gebruik van HondAanZee.be.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/cookies": {
    "title": "Cookiebeleid | HondAanZee.be",
    "description": "Informatie over cookies en bezoekersstatistieken op HondAanZee.be.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/meldpunt/vrijwilligers": {
    "title": "Vrijwilligers voor het meldpunt | HondAanZee.be",
    "description": "Help mee aan een veilige en schone Belgische kust voor honden en hun baasjes.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/updates": {
    "title": "Updates | HondAanZee.be",
    "description": "Bekijk de laatste wijzigingen en aanvullingen op HondAanZee.be.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/blankenberge": {
    "title": "Met je hond naar Blankenberge | Strandregels en hondvriendelijke zaken",
    "description": "Bruisende badstad - strand ten westen van de pier is 24/7 vrij voor honden.",
    "image": "https://hondaanzee.be/blankenberge-new.webp"
  },
  "/zeebrugge": {
    "title": "Met je hond naar Zeebrugge | Strandregels en hondvriendelijke zaken",
    "description": "Breed strand met een jaarrond hondenzone richting Blankenberge.",
    "image": "https://hondaanzee.be/zeebrugge.webp"
  },
  "/knokke-heist": {
    "title": "Met je hond naar Knokke-Heist | Strandregels en hondvriendelijke zaken",
    "description": "De mondaine badstad met luxe beachclubs en een unieke 24/7 losloopzone aan het Zwin.",
    "image": "https://hondaanzee.be/knokke.webp"
  },
  "/de-haan": {
    "title": "Met je hond naar De Haan | Strandregels en hondvriendelijke zaken",
    "description": "Eén van de meest hondvriendelijke badplaatsen - grote onbewaakte stranddelen altijd toegankelijk.",
    "image": "https://hondaanzee.be/dehaan.webp"
  },
  "/wenduine": {
    "title": "Met je hond naar Wenduine | Strandregels en hondvriendelijke zaken",
    "description": "Charmant kustdorpje met gezellige cafés en restaurants waar honden overal welkom zijn.",
    "image": "https://hondaanzee.be/wenduine.webp"
  },
  "/bredene": {
    "title": "Met je hond naar Bredene | Strandregels en hondvriendelijke zaken",
    "description": "Enige badplaats zonder zeedijk - in winter vrij loslopen op strand én in duinen.",
    "image": "https://hondaanzee.be/bredene.webp"
  },
  "/oostende": {
    "title": "Met je hond naar Oostende | Strandregels en hondvriendelijke zaken",
    "description": "Koningin der Badsteden met 3 jaarrond hondenzones: Oosteroever, Klein Strand en Raversijde.",
    "image": "https://hondaanzee.be/oostende.webp"
  },
  "/middelkerke": {
    "title": "Met je hond naar Middelkerke - Westende | Strandregels en hondvriendelijke zaken",
    "description": "Strenge zomerregels, maar 3 uitzonderingszones (Carlton, Sportstrand, Cristal Palace) zijn jaarrond toegankelijk.",
    "image": "https://hondaanzee.be/middelkerke.webp"
  },
  "/nieuwpoort": {
    "title": "Met je hond naar Nieuwpoort | Strandregels en hondvriendelijke zaken",
    "description": "Let op: strengste regels van de kust! In zomer volledig verboden, geen uitzonderingen.",
    "image": "https://hondaanzee.be/nieuwpoort.webp"
  },
  "/koksijde": {
    "title": "Met je hond naar Koksijde - Oostduinkerke | Strandregels en hondvriendelijke zaken",
    "description": "Drie jaarrond hondenzones (±3km totaal) - maar altijd aan leiband (max 10m).",
    "image": "https://hondaanzee.be/oostduinkerke.webp"
  },
  "/de-panne": {
    "title": "Met je hond naar De Panne | Strandregels en hondvriendelijke zaken",
    "description": "Zone 4 (richting Frankrijk) is dé losloopzone - in winter 24/7 vrij, in zomer 's avonds en 's ochtends.",
    "image": "https://hondaanzee.be/depanne.webp"
  },
  "/blankenberge/hotspots/lakaiann": {
    "title": "Lakaiann in Blankenberge | HondAanZee.be",
    "description": "Lakaiann in Blankenberge. Zonder twijfel de meest hondvriendelijke hotspot op de Zeedijk! Hier word je met open armen ontvangen door de allerliefste eigenaars…",
    "image": "https://hondaanzee.be/lakaiannfinal.webp",
    "imageAlt": "Lakaiann in Blankenberge | HondAanZee.be"
  },
  "/nieuwpoort/hotspots/dune-hotel-nieuwpoort": {
    "title": "Dune Hotel Nieuwpoort in Nieuwpoort | HondAanZee.be",
    "description": "Dune Hotel Nieuwpoort in Nieuwpoort. Het Dune Hotel staat bekend om het prachtige uitzicht vanuit de hotelkamers. Word uitgerust wakker, omgeven door de natuur, en…",
    "image": "https://hondaanzee.be/dunehotel.webp",
    "imageAlt": "Dune Hotel Nieuwpoort in Nieuwpoort | HondAanZee.be"
  },
  "/nieuwpoort/hotspots/cosmopolite-hotel": {
    "title": "Cosmopolite Hotel in Nieuwpoort | HondAanZee.be",
    "description": "Cosmopolite Hotel in Nieuwpoort. Een begrip aan de Belgische kust met een traditie van 100 jaar gastvrijheid! Dit 4 sterren hotel combineert luxe met een…",
    "image": "https://hondaanzee.be/cosmopolite.webp",
    "imageAlt": "Cosmopolite Hotel in Nieuwpoort | HondAanZee.be"
  },
  "/middelkerke/hotspots/beachbar-de-kwinte": {
    "title": "Beachbar De Kwinte in Middelkerke - Westende | HondAanZee.be",
    "description": "Beachbar De Kwinte in Middelkerke - Westende. Geniet van lokale gerechten terwijl je hond rustig onder tafel ligt.",
    "image": "https://hondaanzee.be/dekwintemiddelkerke.webp",
    "imageAlt": "Beachbar De Kwinte in Middelkerke - Westende | HondAanZee.be"
  },
  "/middelkerke/hotspots/madam-caravan": {
    "title": "Madam Caravan in Middelkerke - Westende | HondAanZee.be",
    "description": "Madam Caravan in Middelkerke - Westende. Een kleinere koffiebar met een gigantisch groot hart voor honden! De eigenares heeft zelf ook een trouwe viervoeter en…",
    "image": "https://hondaanzee.be/caravan.webp",
    "imageAlt": "Madam Caravan in Middelkerke - Westende | HondAanZee.be"
  },
  "/middelkerke/hotspots/de-frietboetiek": {
    "title": "De Frietboetiek in Middelkerke - Westende | HondAanZee.be",
    "description": "De Frietboetiek in Middelkerke - Westende. Een échte familiezaak met extreem lekkere huisbereide burgers van Dierendonck's rundsvlees en huisgemaakte sauzen die je…",
    "image": "https://hondaanzee.be/frietboetiek.webp",
    "imageAlt": "De Frietboetiek in Middelkerke - Westende | HondAanZee.be"
  },
  "/oostende/hotspots/bistrot-de-la-mer": {
    "title": "Bistrot de la Mer in Oostende | HondAanZee.be",
    "description": "Bistrot de la Mer in Oostende. Sfeervol restaurant waar u samen met uw hond geniet van dagverse visgerechten en schaaldieren.",
    "image": "https://hondaanzee.be/bistrotdelameroostende.webp",
    "imageAlt": "Bistrot de la Mer in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/c-hotels-andromeda": {
    "title": "C-Hotels Andromeda in Oostende | HondAanZee.be",
    "description": "C-Hotels Andromeda in Oostende. Luxe hotel aan de zeedijk waar honden (max. 10kg) van harte welkom zijn op de kamer.",
    "image": "https://hondaanzee.be/c-hotelsandromedaoostende.webp",
    "imageAlt": "C-Hotels Andromeda in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/gastrobar-sam": {
    "title": "Gastrobar Sam in Oostende | HondAanZee.be",
    "description": "Gastrobar Sam in Oostende. Hondvriendelijke gastrobar in Oostende waar je hond welkom is, binnen en op het terras.",
    "image": "https://hondaanzee.be/gastrobarsam1.webp",
    "imageAlt": "Gastrobar Sam in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/upstairs-hotel": {
    "title": "Upstairs Hotel in Oostende | HondAanZee.be",
    "description": "Upstairs Hotel in Oostende. Hip en modern hotel vlakbij het strand waar honden welkom zijn in specifieke kamertypes.",
    "image": "https://hondaanzee.be/upstairshoteloostende.webp",
    "imageAlt": "Upstairs Hotel in Oostende | HondAanZee.be"
  },
  "/knokke-heist/hotspots/siesta-bar": {
    "title": "Siesta Bar in Knokke-Heist | HondAanZee.be",
    "description": "Siesta Bar in Knokke-Heist. Unieke tapasbar die beroemd is om zijn speciale hondenmenu met snacks en 'hondenbier'.",
    "image": "https://hondaanzee.be/siestabarknokke.webp",
    "imageAlt": "Siesta Bar in Knokke-Heist | HondAanZee.be"
  },
  "/knokke-heist/hotspots/brasserie-rubens": {
    "title": "Brasserie Rubens in Knokke-Heist | HondAanZee.be",
    "description": "Brasserie Rubens in Knokke-Heist. Een vaste waarde in Knokke waar u en uw hond kunnen genieten van klassieke brasseriegerechten.",
    "image": "https://hondaanzee.be/brasserierubensknokke.webp",
    "imageAlt": "Brasserie Rubens in Knokke-Heist | HondAanZee.be"
  },
  "/blankenberge/hotspots/belgium-pier-brasserie": {
    "title": "Belgium Pier Brasserie in Blankenberge | HondAanZee.be",
    "description": "Belgium Pier Brasserie in Blankenberge. Brasserie op de iconische pier van Blankenberge waar je letterlijk boven zee eet en de locatie al de helft van de ervaring…",
    "image": "https://hondaanzee.be/belgianpierbrasserieblankenberge.webp",
    "imageAlt": "Belgium Pier Brasserie in Blankenberge | HondAanZee.be"
  },
  "/de-panne/hotspots/de-verloren-gernoare": {
    "title": "De Verloren Gernoare in De Panne | HondAanZee.be",
    "description": "De Verloren Gernoare in De Panne. Authentiek bruin café/estaminet waar honden als 'thuis' worden ontvangen door de uitbater.",
    "image": "https://hondaanzee.be/brasserieDeVerlorenGernoaredepanne.webp",
    "imageAlt": "De Verloren Gernoare in De Panne | HondAanZee.be"
  },
  "/nieuwpoort/hotspots/brasserie-carrousel": {
    "title": "Brasserie Carrousel in Nieuwpoort | HondAanZee.be",
    "description": "Brasserie Carrousel in Nieuwpoort. Populaire brasserie waar honden overal welkom zijn! Voor het ontbijt hebben ze zelfs een extra ruimte waar je rustig kunt…",
    "image": "https://hondaanzee.be/brasseriecarrouselnieuwpoort.webp",
    "imageAlt": "Brasserie Carrousel in Nieuwpoort | HondAanZee.be"
  },
  "/nieuwpoort/hotspots/brasserie-het-kompas": {
    "title": "Brasserie Het Kompas in Nieuwpoort | HondAanZee.be",
    "description": "Brasserie Het Kompas in Nieuwpoort. Gezellig tafelen op de Zeedijk, maximaal één hond per tafel toegelaten.",
    "image": "https://hondaanzee.be/brasseriehetkompasnieuwpoort.webp",
    "imageAlt": "Brasserie Het Kompas in Nieuwpoort | HondAanZee.be"
  },
  "/nieuwpoort/hotspots/cafe-au-blason": {
    "title": "Café Au Blason in Nieuwpoort | HondAanZee.be",
    "description": "Café Au Blason in Nieuwpoort. Een authentieke bruine kroeg zoals een café hoort te zijn! Au Blason staat bekend als een sfeervolle bar in Nieuwpoort waar jong en…",
    "image": "https://hondaanzee.be/aublason2.webp",
    "imageAlt": "Café Au Blason in Nieuwpoort | HondAanZee.be"
  },
  "/nieuwpoort/hotspots/cremerie-artisanaal-ijs": {
    "title": "Cremerie Artisanaal Ijs in Nieuwpoort | HondAanZee.be",
    "description": "Cremerie Artisanaal Ijs in Nieuwpoort. Een heerlijk adresje voor de zoetekauwen! Bij Cremerie geniet je van het allerlekkerste artisanale ijs, krokante Luikse…",
    "image": "https://hondaanzee.be/cremerie.webp",
    "imageAlt": "Cremerie Artisanaal Ijs in Nieuwpoort | HondAanZee.be"
  },
  "/nieuwpoort/hotspots/bar-buvette": {
    "title": "Bar Buvette in Nieuwpoort | HondAanZee.be",
    "description": "Bar Buvette in Nieuwpoort. Een ruime en gezellige zaak op de Albert I laan waar je met je viervoeter terecht kan voor een ontspannen moment. Bar Buvette biedt een…",
    "image": "https://hondaanzee.be/buvette.webp",
    "imageAlt": "Bar Buvette in Nieuwpoort | HondAanZee.be"
  },
  "/nieuwpoort/hotspots/de-vismarkt-aan-zee": {
    "title": "De Vismarkt Aan Zee in Nieuwpoort | HondAanZee.be",
    "description": "De Vismarkt Aan Zee in Nieuwpoort. Modern en eigentijds café waar je heerlijk kunt wegdromen met een goed glas wijn, een fris pintje of een perfecte koffie…",
    "image": "https://hondaanzee.be/vismarkt.webp",
    "imageAlt": "De Vismarkt Aan Zee in Nieuwpoort | HondAanZee.be"
  },
  "/middelkerke/hotspots/bistro-noordzee": {
    "title": "Bistro Noordzee in Middelkerke - Westende | HondAanZee.be",
    "description": "Bistro Noordzee in Middelkerke - Westende. Bekende bistro op de zeedijk met prachtig zicht op zee en een groot hart voor dieren, perfect na een strandwandeling…",
    "image": "https://hondaanzee.be/bistrotnoordzeemiddelkerke.webp",
    "imageAlt": "Bistro Noordzee in Middelkerke - Westende | HondAanZee.be"
  },
  "/middelkerke/hotspots/de-lekpot": {
    "title": "De Lekpot in Middelkerke - Westende | HondAanZee.be",
    "description": "De Lekpot in Middelkerke - Westende. Een gezellig familierestaurant met een super vriendelijke eigenaar en een gigantisch groot hart voor honden! Gespecialiseerd…",
    "image": "https://hondaanzee.be/delekpotmiddelkerke.webp",
    "imageAlt": "De Lekpot in Middelkerke - Westende | HondAanZee.be"
  },
  "/middelkerke/hotspots/bistra-liva": {
    "title": "Bistra Liva in Middelkerke - Westende | HondAanZee.be",
    "description": "Bistra Liva in Middelkerke - Westende. Gezellige bistro op de Zeedijk waar \"Liva\" staat voor liefde voor allen – en dat geldt zeker ook voor je viervoeter! Geniet…",
    "image": "https://hondaanzee.be/bistraliva.webp",
    "imageAlt": "Bistra Liva in Middelkerke - Westende | HondAanZee.be"
  },
  "/de-haan/hotspots/restaurant-de-concessie": {
    "title": "Restaurant De Concessie in De Haan | HondAanZee.be",
    "description": "Restaurant De Concessie in De Haan. Stijlvol genieten in het historische hart van De Haan, honden zijn hier toegelaten.",
    "image": "https://hondaanzee.be/restaurantdeconcessiedehaan.webp",
    "imageAlt": "Restaurant De Concessie in De Haan | HondAanZee.be"
  },
  "/de-haan/hotspots/ibis-hotel": {
    "title": "Ibis Hotel in De Haan | HondAanZee.be",
    "description": "Ibis Hotel in De Haan. Modern en comfortabel hotel met 83 eigentijdse kamers, elk voorzien van airco, gratis WiFi en smart tv. Ontspan in het verwarmde…",
    "image": "https://hondaanzee.be/ibisdehaan.webp",
    "imageAlt": "Ibis Hotel in De Haan | HondAanZee.be"
  },
  "/de-haan/hotspots/pizzeria-piano-piano": {
    "title": "Pizzeria Piano Piano in De Haan | HondAanZee.be",
    "description": "Pizzeria Piano Piano in De Haan. Authentieke Italiaanse pizzeria met 34 jaar ervaring en een hart van goud. Dit warme familiebedrijf, nu overgenomen door de nieuwe…",
    "image": "https://hondaanzee.be/pianopiano.webp",
    "imageAlt": "Pizzeria Piano Piano in De Haan | HondAanZee.be"
  },
  "/de-haan/hotspots/plaza-d-amante": {
    "title": "Plaza d'Amanté in De Haan | HondAanZee.be",
    "description": "Plaza d'Amanté in De Haan. Een pareltje op de Zeedijk van De Haan waar specialty coffee, lokale producten en een warm hart voor honden samenkomen. De super lieve…",
    "image": "https://hondaanzee.be/plazaamante.webp",
    "imageAlt": "Plaza d'Amanté in De Haan | HondAanZee.be"
  },
  "/blankenberge/hotspots/cozy-moments": {
    "title": "Cozy Moments in Blankenberge | HondAanZee.be",
    "description": "Cozy Moments in Blankenberge. Super gezellige koffie- en cocktailbar op de Grote Markt, waar je makkelijk even neerstrijkt met je hond. Pal in het midden van…",
    "image": "https://hondaanzee.be/sixtines.webp",
    "imageAlt": "Cozy Moments in Blankenberge | HondAanZee.be"
  },
  "/bredene/hotspots/alaska": {
    "title": "Alaska in Bredene | HondAanZee.be",
    "description": "Alaska in Bredene. Authentiek eethuis en frituur in het hart van Bredene waar je hond welkom is terwijl jij geniet van klassieke Belgische gerechten en verse…",
    "image": "https://hondaanzee.be/alaska.webp",
    "imageAlt": "Alaska in Bredene | HondAanZee.be"
  },
  "/bredene/hotspots/coffee-wine-de-golf": {
    "title": "Coffee & Wine De Golf in Bredene | HondAanZee.be",
    "description": "Coffee & Wine De Golf in Bredene. Stijlvolle zaak waar je overdag kunt genieten van een heerlijke koffie en 's avonds van een goed glas wijn. Honden zijn hier…",
    "image": "https://hondaanzee.be/coffeewinedegolf.webp",
    "imageAlt": "Coffee & Wine De Golf in Bredene | HondAanZee.be"
  },
  "/bredene/hotspots/brasserie-shop-n-lunch-p-p": {
    "title": "Brasserie Shop 'n Lunch P&P in Bredene | HondAanZee.be",
    "description": "Brasserie Shop 'n Lunch P&P in Bredene. Gezellige zaak waar je kunt genieten van een heerlijk ontbijt, verse koffie en smakelijke broodjes.Daarnaast worden ook…",
    "image": "https://hondaanzee.be/shopnlunch.webp",
    "imageAlt": "Brasserie Shop 'n Lunch P&P in Bredene | HondAanZee.be"
  },
  "/oostende/hotspots/mercure-oostende": {
    "title": "Mercure Oostende in Oostende | HondAanZee.be",
    "description": "Mercure Oostende in Oostende. Modern 4-sterrenhotel in het centrum, vlakbij het strand en het casino. Huisdieren zijn welkom in dit comfortabele hotel met…",
    "image": "https://hondaanzee.be/mercurehotel.webp",
    "imageAlt": "Mercure Oostende in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/hotel-pacific": {
    "title": "Hotel Pacific in Oostende | HondAanZee.be",
    "description": "Hotel Pacific in Oostende. Gezellig driesterrenhotel op 50 meter van het strand. Perfect voor een ontspannen verblijf met je viervoeter aan zee.",
    "image": "https://hondaanzee.be/hotelpacific.webp",
    "imageAlt": "Hotel Pacific in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/hotel-royal-astrid": {
    "title": "Hotel Royal Astrid in Oostende | HondAanZee.be",
    "description": "Hotel Royal Astrid in Oostende. 3-sterrenhotel met wellnessfaciliteiten (1000m²), gelegen nabij het strand. Geniet van ontspanning terwijl je hond welkom is.",
    "image": "https://hondaanzee.be/hotelroyalastrid.webp",
    "imageAlt": "Hotel Royal Astrid in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/hotel-albert-ii": {
    "title": "Hotel Albert II in Oostende | HondAanZee.be",
    "description": "Hotel Albert II in Oostende. Historisch pand met Belle Époque sfeer in het centrum, vlakbij de markt. Een charmant hotel waar geschiedenis en comfort samenkomen.",
    "image": "https://hondaanzee.be/hotelalbert2.webp",
    "imageAlt": "Hotel Albert II in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/charmehotel-t-kruishof": {
    "title": "Charmehotel 't Kruishof in Oostende | HondAanZee.be",
    "description": "Charmehotel 't Kruishof in Oostende. Gelegen tussen stad en polders, met veel ruimte en groen. Ideaal voor wandelingen met je hond in een rustige omgeving.",
    "image": "https://hondaanzee.be/charmehotelkruishof.webp",
    "imageAlt": "Charmehotel 't Kruishof in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/b-b-huyze-elimonica": {
    "title": "B&B Huyze Elimonica in Oostende | HondAanZee.be",
    "description": "B&B Huyze Elimonica in Oostende. Stijlvolle B&B in een geklasseerd pand uit 1899, hondvriendelijk. Geniet van de charme van een historisch gebouw met moderne…",
    "image": "https://hondaanzee.be/huyzeelimonica.webp",
    "imageAlt": "B&B Huyze Elimonica in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/villa-cecha-b-b-wellness": {
    "title": "Villa Cecha B&B & Wellness in Oostende | HondAanZee.be",
    "description": "Villa Cecha B&B & Wellness in Oostende. Kleinschalige B&B met wellness in het rustige Stene-dorp. Perfect voor een ontspannen uitje met je viervoeter.",
    "image": "https://hondaanzee.be/villacecha.webp",
    "imageAlt": "Villa Cecha B&B & Wellness in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/maison-martha": {
    "title": "Maison Martha in Oostende | HondAanZee.be",
    "description": "Maison Martha in Oostende. Ruime vakantiewoning (tot 12 personen) met sauna en jacuzzi. Ideaal voor een groepsverblijf met je hond.",
    "image": "https://hondaanzee.be/maisonmartha.webp",
    "imageAlt": "Maison Martha in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/villa-odette": {
    "title": "Villa Odette in Oostende | HondAanZee.be",
    "description": "Villa Odette in Oostende. Luxe vakantiehuis voor grote groepen (tot 14 personen), ingericht in beach-style. Perfect voor een strandvakantie met familie en hond.",
    "image": "https://hondaanzee.be/villaodette.webp",
    "imageAlt": "Villa Odette in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/sea-breeze": {
    "title": "Sea Breeze in Oostende | HondAanZee.be",
    "description": "Sea Breeze in Oostende. Appartement in het centrum, op wandelafstand van de zeedijk. Ideale uitvalsbasis voor een stedentrip met je hond.",
    "image": "https://hondaanzee.be/seabreeze.webp",
    "imageAlt": "Sea Breeze in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/zilte-stilte": {
    "title": "Zilte Stilte in Oostende | HondAanZee.be",
    "description": "Zilte Stilte in Oostende. Vakantiewoning met focus op rust, huisdieren welkom. Geniet van een rustige vakantie in een hondvriendelijke omgeving.",
    "image": "https://hondaanzee.be/ziltestilte.webp",
    "imageAlt": "Zilte Stilte in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/les-cabanes-d-ostende": {
    "title": "Les Cabanes d'Ostende in Oostende | HondAanZee.be",
    "description": "Les Cabanes d'Ostende in Oostende. Unieke 'cabins' in het groen nabij het Ensorpark, een oase van rust aan de rand van de stad. Bijzondere ervaring voor jou en je…",
    "image": "https://hondaanzee.be/lescabanes.webp",
    "imageAlt": "Les Cabanes d'Ostende in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/taverne-de-klokke": {
    "title": "Taverne De Klokke in Oostende | HondAanZee.be",
    "description": "Taverne De Klokke in Oostende. Authentieke bruine kroeg/brasserie waar je hond welkom is. Geniet van een gezellige sfeer en klassieke gerechten.",
    "image": "https://hondaanzee.be/tavernedeklokke.webp",
    "imageAlt": "Taverne De Klokke in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/yuzu": {
    "title": "Yuzu in Oostende | HondAanZee.be",
    "description": "Yuzu in Oostende. Sushi en seafood restaurant, fusion van Japans en Frans-Belgisch. Je hond mag mee genieten van deze culinaire ervaring.",
    "image": "https://hondaanzee.be/yuzu.webp",
    "imageAlt": "Yuzu in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/brasserie-david": {
    "title": "Brasserie David in Oostende | HondAanZee.be",
    "description": "Brasserie David in Oostende. Gezellige zaak met klassieke gerechten en verse vis. Je viervoeter is hier van harte welkom.",
    "image": "https://hondaanzee.be/brasseriedavid.webp",
    "imageAlt": "Brasserie David in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/moby-dick": {
    "title": "Moby Dick in Oostende | HondAanZee.be",
    "description": "Moby Dick in Oostende. Bekend visrestaurant met een toog in de vorm van een vissersboot. Een unieke ervaring waar je hond welkom is.",
    "image": "https://hondaanzee.be/mobydick.webp",
    "imageAlt": "Moby Dick in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/bottarga": {
    "title": "Bottarga in Oostende | HondAanZee.be",
    "description": "Bottarga in Oostende. Trendy brasserie op de zeedijk met zeezicht. Geniet van een heerlijke maaltijd terwijl je uitkijkt over zee met je hond naast je.",
    "image": "https://hondaanzee.be/bottarga.webp",
    "imageAlt": "Bottarga in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/cappuccino-rooftop-bar": {
    "title": "Cappuccino Rooftop Bar in Oostende | HondAanZee.be",
    "description": "Cappuccino Rooftop Bar in Oostende. Tearoom en rooftop bar voor ontbijt, wafels en cocktails. Je hond mag mee genieten van het uitzicht.",
    "image": "https://hondaanzee.be/cappuccinorooftopbar.webp",
    "imageAlt": "Cappuccino Rooftop Bar in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/han-s-centrum": {
    "title": "HAN's centrum in Oostende | HondAanZee.be",
    "description": "HAN's centrum in Oostende. Gezonde lunch, soep en boterhammen. Perfect voor een snelle, gezonde hap met je viervoeter.",
    "image": "https://hondaanzee.be/hanscentrum.webp",
    "imageAlt": "HAN's centrum in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/lloyd-coffee-eatery": {
    "title": "Lloyd Coffee Eatery in Oostende | HondAanZee.be",
    "description": "Lloyd Coffee Eatery in Oostende. Moderne coffee eatery in het centrum van Oostende voor specialty coffee, huisgemaakte brunchgerechten en een ontspannen stop waar…",
    "image": "https://hondaanzee.be/lloydcoffeeeatery.webp",
    "imageAlt": "Lloyd Coffee Eatery in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/meerman-specialty-coffee": {
    "title": "Meerman Specialty Coffee in Oostende | HondAanZee.be",
    "description": "Meerman Specialty Coffee in Oostende. Warme specialty coffee bar in de Christinastraat met matcha, thee en een gezellig welkom voor honden.",
    "image": "https://hondaanzee.be/meerman2.avif",
    "imageAlt": "Meerman Specialty Coffee in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/manuscript": {
    "title": "Manuscript in Oostende | HondAanZee.be",
    "description": "Manuscript in Oostende. Authentiek bruin café in de Langestraat met een indrukwekkende bierkaart, een vaste liefde voor rock, blues en jazz, en een sfeer die veel…",
    "image": "https://hondaanzee.be/manuscript.jpg",
    "imageAlt": "Manuscript in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/restaurant-de-golf": {
    "title": "Restaurant De Golf in Oostende | HondAanZee.be",
    "description": "Restaurant De Golf in Oostende. Restaurant op de zeedijk van Mariakerke met zeezicht, doorlopende keuken en uitzonderlijk veel aandacht voor honden, inclusief…",
    "image": "https://hondaanzee.be/degolf.webp",
    "imageAlt": "Restaurant De Golf in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/restaurant-le-touquet": {
    "title": "Restaurant Le Touquet in Oostende | HondAanZee.be",
    "description": "Restaurant Le Touquet in Oostende. Traditioneel restaurant op de Albert I-promenade met lokale producten, verwarmd terras en een opvallend makkelijke ontvangst…",
    "image": "https://hondaanzee.be/letouqet.webp",
    "imageAlt": "Restaurant Le Touquet in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/de-witte-ezel": {
    "title": "De Witte Ezel in Oostende | HondAanZee.be",
    "description": "De Witte Ezel in Oostende. Charmant restaurant-tearoom in Gistel (vlakbij Oostende) waar je met je viervoeter terecht kan voor een heerlijk ontbijt, een verzorgde…",
    "image": "https://hondaanzee.be/witteezel.jpeg",
    "imageAlt": "De Witte Ezel in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/la-vie": {
    "title": "La Vie in Oostende | HondAanZee.be",
    "description": "La Vie in Oostende. Hedendaagse tapasbar vlak bij de zeedijk waar sharing, cocktails en een losse avondsfeer centraal staan, zonder dat het zwaar of pretentieus…",
    "image": "https://hondaanzee.be/lavie.webp",
    "imageAlt": "La Vie in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/gastro-na-jo": {
    "title": "Gastro Na'Jo in Oostende | HondAanZee.be",
    "description": "Gastro Na'Jo in Oostende. Kleinschalige gastrozaak in Stene met een beperkte kwaliteitskaart, snel wisselende suggesties en een rustige, hondvriendelijke sfeer.",
    "image": "https://hondaanzee.be/najov2.jpeg",
    "imageAlt": "Gastro Na'Jo in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/residence-du-centre": {
    "title": "Residence Du Centre in Oostende | HondAanZee.be",
    "description": "Residence Du Centre in Oostende. Gezellig vakantieappartement op toplocatie in het centrum van Oostende, met het grootste pluspunt: een ruim terras waar je…",
    "image": "https://hondaanzee.be/app_oostende.webp",
    "imageAlt": "Residence Du Centre in Oostende | HondAanZee.be"
  },
  "/blankenberge/hotspots/grand-cafe": {
    "title": "Grand Café in Blankenberge | HondAanZee.be",
    "description": "Grand Café in Blankenberge. Grote zaak op de zeedijk met klassieke brasseriesfeer, brede kaart en extra aandacht voor honden, tot en met een eigen gerechtje.",
    "image": "https://hondaanzee.be/grandcafecover.webp",
    "imageAlt": "Grand Café in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/fondue-co-t-keteltje": {
    "title": "Fondue & Co 't Keteltje in Blankenberge | HondAanZee.be",
    "description": "Fondue & Co 't Keteltje in Blankenberge. Huiselijk restaurant vlak bij het strand waar eerlijke keuken, persoonlijke service en fondue centraal staan.",
    "image": "https://hondaanzee.be/fonduetketeltje.webp",
    "imageAlt": "Fondue & Co 't Keteltje in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/frituur-sparkle-chips": {
    "title": "Frituur Sparkle Chips in Blankenberge | HondAanZee.be",
    "description": "Frituur Sparkle Chips in Blankenberge. Moderne frituur op de Zeedijk waar je kunt genieten van krokante frietjes en klassieke frituursnacks. Je hond mag mee…",
    "image": "https://hondaanzee.be/frituursparklechips.webp",
    "imageAlt": "Frituur Sparkle Chips in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/de-sleutel-la-clef": {
    "title": "De Sleutel & La Clef in Blankenberge | HondAanZee.be",
    "description": "De Sleutel & La Clef in Blankenberge. Klassiek restaurant op de zeedijk met uitzicht op zee, een brede kaart en een lange familiegeschiedenis in Blankenberge.",
    "image": "https://hondaanzee.be/desleutel.webp",
    "imageAlt": "De Sleutel & La Clef in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/frituur-taste": {
    "title": "Frituur Taste in Blankenberge | HondAanZee.be",
    "description": "Frituur Taste in Blankenberge. Populaire frituur in het centrum waar kwaliteit en smaak voorop staan. Geniet van verse frietjes en een ruim aanbod aan snacks…",
    "image": "https://hondaanzee.be/tasteV2.webp",
    "imageAlt": "Frituur Taste in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/huisje-van-majutte": {
    "title": "Huisje van Majutte in Blankenberge | HondAanZee.be",
    "description": "Huisje van Majutte in Blankenberge. Stap binnen in het oudste vissershuisje van de kust (1775) en laat je terugvoeren in de tijd. Gastheer Luc en gastvrouw…",
    "image": "https://hondaanzee.be/majutte.webp",
    "imageAlt": "Huisje van Majutte in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/tearoom-koffiepotje": {
    "title": "Tearoom Koffiepotje in Blankenberge | HondAanZee.be",
    "description": "Tearoom Koffiepotje in Blankenberge. Charmante tearoom waar je kunt genieten van verse koffie, thee en heerlijke gebakjes. Een rustige plek om even uit te rusten…",
    "image": "https://hondaanzee.be/koffiepotje.webp",
    "imageAlt": "Tearoom Koffiepotje in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/my-home-my-coffee": {
    "title": "My Home My Coffee in Blankenberge | HondAanZee.be",
    "description": "My Home My Coffee in Blankenberge. Kleine koffiebar met woonkamergevoel waar specialty coffee, rust en een heel persoonlijke ontvangst belangrijker zijn dan…",
    "image": "https://hondaanzee.be/myhomemycoffee.webp",
    "imageAlt": "My Home My Coffee in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/b-b-chez-ba-nus": {
    "title": "B&B Chez Ba'Nus in Blankenberge | HondAanZee.be",
    "description": "B&B Chez Ba'Nus in Blankenberge. Persoonlijke B&B op wandelafstand van zee met themakamers, verzorgd ontbijt en een ontvangst waar honden echt mee zijn ingedacht.",
    "image": "https://hondaanzee.be/chezbanusV3.webp",
    "imageAlt": "B&B Chez Ba'Nus in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/vakantieappartement-ld383277": {
    "title": "Vakantieappartement LD383277 in Blankenberge | HondAanZee.be",
    "description": "Vakantieappartement LD383277 in Blankenberge. Comfortabel vakantieappartement ideaal gelegen nabij het Leopoldpark, lunapark en strandbars. Perfect voor een…",
    "image": "https://hondaanzee.be/LD383277.webp",
    "imageAlt": "Vakantieappartement LD383277 in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/vakantieappartement-maison-clementine": {
    "title": "Vakantieappartement Maison Clementine in Blankenberge | HondAanZee.be",
    "description": "Vakantieappartement Maison Clementine in Blankenberge. Luxueus ingericht appartement met alle voorzieningen, vlakbij de haven van Blankenberge. Geniet van het…",
    "image": "https://hondaanzee.be/maisonclementine.webp",
    "imageAlt": "Vakantieappartement Maison Clementine in Blankenberge | HondAanZee.be"
  },
  "/wenduine/hotspots/brasserie-eloise": {
    "title": "Brasserie Eloïse in Wenduine | HondAanZee.be",
    "description": "Brasserie Eloïse in Wenduine. Charmante brasserie in het hart van Wenduine waar kleine honden van harte welkom zijn! Geniet van een gezellige sfeer en heerlijke…",
    "image": "https://hondaanzee.be/eloise.webp",
    "imageAlt": "Brasserie Eloïse in Wenduine | HondAanZee.be"
  },
  "/bredene/hotspots/hippo-12": {
    "title": "Hippo 12 in Bredene | HondAanZee.be",
    "description": "Hippo 12 in Bredene. Gezellig café met een levendige sfeer waar je kunt genieten van heerlijke cocktails en live muziek. Het ruime buitenterras is perfect om te…",
    "image": "https://hondaanzee.be/hippo12.webp",
    "imageAlt": "Hippo 12 in Bredene | HondAanZee.be"
  },
  "/knokke-heist/hotspots/bar-delta": {
    "title": "Bar Delta in Knokke-Heist | HondAanZee.be",
    "description": "Bar Delta in Knokke-Heist. Gezellige bar aan het einde van de zeedijk in Heist, richting Zeebrugge. Perfect om even tot rust te komen met een hele lekkere koffie…",
    "image": "https://hondaanzee.be/bardeltaV2.webp",
    "imageAlt": "Bar Delta in Knokke-Heist | HondAanZee.be"
  },
  "/blankenberge/hotspots/sea-sparkle": {
    "title": "Sea Sparkle in Blankenberge | HondAanZee.be",
    "description": "Sea Sparkle in Blankenberge. Prachtig afgewerkt vakantieappartement met adembenemend zeezicht voor maximaal zes personen. Chris en Tatiana verwennen hun gasten…",
    "image": "https://hondaanzee.be/seasparkle.webp",
    "imageAlt": "Sea Sparkle in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/pancho": {
    "title": "Pancho in Blankenberge | HondAanZee.be",
    "description": "Pancho in Blankenberge. Charmant vakantieappartement dat alle comfort biedt voor vier personen op een boogscheut van het strand. Chris en Tatiana verhuren dit…",
    "image": "https://hondaanzee.be/pancho.webp",
    "imageAlt": "Pancho in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/casa-mati": {
    "title": "Casa MaTi in Blankenberge | HondAanZee.be",
    "description": "Casa MaTi in Blankenberge. Knus vakantieappartement op enkele minuten van het strand, met alle comfort voor een onvergetelijke strandvakantie. Het appartement…",
    "image": "https://hondaanzee.be/casamati.webp",
    "imageAlt": "Casa MaTi in Blankenberge | HondAanZee.be"
  },
  "/oostende/hotspots/restaurant-t-pomptje": {
    "title": "Restaurant 't Pomptje in Oostende | HondAanZee.be",
    "description": "Restaurant 't Pomptje in Oostende. Rustiek restaurant in Stene dat bekendstaat om gemarineerde ribbetjes, gegrilde gerechten en een uitgesproken persoonlijke sfeer…",
    "image": "https://hondaanzee.be/tpomptje.webp",
    "imageAlt": "Restaurant 't Pomptje in Oostende | HondAanZee.be"
  },
  "/wenduine/hotspots/tearoom-wielingen-bar": {
    "title": "Tearoom Wielingen Bar in Wenduine | HondAanZee.be",
    "description": "Tearoom Wielingen Bar in Wenduine. Gezellige tearoom en restaurant gelegen aan het zwembad van Wenduine, met twee grote windvrije terrassen in een aangenaam kader…",
    "image": "https://hondaanzee.be/wielingenbar.webp",
    "imageAlt": "Tearoom Wielingen Bar in Wenduine | HondAanZee.be"
  },
  "/wenduine/hotspots/maison-elza": {
    "title": "Maison Elza in Wenduine | HondAanZee.be",
    "description": "Maison Elza in Wenduine. Hippe nieuwe koffiebar in het hart van Wenduine waar je kunt genieten van heerlijke specialty coffee en huisgemaakte lekkernijen. Een…",
    "image": "https://hondaanzee.be/maisonelza.webp",
    "imageAlt": "Maison Elza in Wenduine | HondAanZee.be"
  },
  "/wenduine/hotspots/cafe-central": {
    "title": "Café Central in Wenduine | HondAanZee.be",
    "description": "Café Central in Wenduine. Authentiek volkscafé met een fantastische eigenaar met een groot hart voor honden. Hier proef je de echte Vlaamse cafésfeer waar iedereen…",
    "image": "https://hondaanzee.be/central.webp",
    "imageAlt": "Café Central in Wenduine | HondAanZee.be"
  },
  "/wenduine/hotspots/praatcafe-de-spioenkop": {
    "title": "Praatcafé De Spioenkop in Wenduine | HondAanZee.be",
    "description": "Praatcafé De Spioenkop in Wenduine. Gezellig praatcafé op de Zeedijk met een heerlijke ambiance en prachtig zicht op zee. De volkse sfeer en hartelijke eigenaars…",
    "image": "https://hondaanzee.be/spioenkop.webp",
    "imageAlt": "Praatcafé De Spioenkop in Wenduine | HondAanZee.be"
  },
  "/wenduine/hotspots/de-zoete-zonde": {
    "title": "De Zoete Zonde in Wenduine | HondAanZee.be",
    "description": "De Zoete Zonde in Wenduine. Knus café waar je komt voor de gezellige sfeer en heerlijke koffie. De fantastische eigenaars zorgen ervoor dat iedereen zich thuis…",
    "image": "https://hondaanzee.be/zoetezonde.webp",
    "imageAlt": "De Zoete Zonde in Wenduine | HondAanZee.be"
  },
  "/wenduine/hotspots/bistro-thuus": {
    "title": "Bistro THUUS in Wenduine | HondAanZee.be",
    "description": "Bistro THUUS in Wenduine. Bistro THUUS voelt als thuiskomen, maar dan zonder de afwas! De eigenaars zijn zelf trotse baasjes van Tess, hun Golden Retriever, en…",
    "image": "https://hondaanzee.be/bistrothuus.webp",
    "imageAlt": "Bistro THUUS in Wenduine | HondAanZee.be"
  },
  "/wenduine/hotspots/vissershuisje-89": {
    "title": "Vissershuisje 89 in Wenduine | HondAanZee.be",
    "description": "Vissershuisje 89 in Wenduine. Charmant vissershuisje in het rustige Zeepark Haerendycke, perfect gelegen tussen Wenduine en Blankenberge. De ideale uitvalsbasis…",
    "image": "https://hondaanzee.be/vissershuisje.jpeg",
    "imageAlt": "Vissershuisje 89 in Wenduine | HondAanZee.be"
  },
  "/blankenberge/hotspots/brasserie-bon-appetit": {
    "title": "Brasserie Bon Appetit in Blankenberge | HondAanZee.be",
    "description": "Brasserie Bon Appetit in Blankenberge. Genieten met zicht op zee en je trouwe viervoeter aan je zijde? Bij Brasserie Bon Appetit op de Zeedijk van Blankenberge ben…",
    "image": "https://hondaanzee.be/bonappetit.webp",
    "imageAlt": "Brasserie Bon Appetit in Blankenberge | HondAanZee.be"
  },
  "/de-panne/hotspots/vakantiehuis-zee-hond": {
    "title": "Vakantiehuis Zee-Hond in De Panne | HondAanZee.be",
    "description": "Vakantiehuis Zee-Hond in De Panne. Hondvriendelijk vakantiehuisje in De Panne met een mooie grote tuin. Op 3 km van het centrum, met een supermarkt in de straat…",
    "image": "https://hondaanzee.be/zee-hond.webp",
    "imageAlt": "Vakantiehuis Zee-Hond in De Panne | HondAanZee.be"
  },
  "/middelkerke/hotspots/bungalowpark-jonckershof": {
    "title": "Bungalowpark Jonckershof in Middelkerke - Westende | HondAanZee.be",
    "description": "Bungalowpark Jonckershof in Middelkerke - Westende. Geniet samen met je hond van een heerlijke vakantie in Westende-Bad. Jonckershof is een uitgestrekt domein (11…",
    "image": "https://hondaanzee.be/jonckershof.webp",
    "imageAlt": "Bungalowpark Jonckershof in Middelkerke - Westende | HondAanZee.be"
  },
  "/knokke-heist/hotspots/surfers-paradise": {
    "title": "Surfers Paradise in Knokke-Heist | HondAanZee.be",
    "description": "Surfers Paradise in Knokke-Heist. Terwijl jij geniet van een cocktail in de Sunset lounge, kan je hond heerlijk bij de zitzakken of hangmatten liggen. Het is de…",
    "image": "https://hondaanzee.be/surfersparadise.webp",
    "imageAlt": "Surfers Paradise in Knokke-Heist | HondAanZee.be"
  },
  "/knokke-heist/hotspots/zaelig-hotel": {
    "title": "ZAELIG Hotel in Knokke-Heist | HondAanZee.be",
    "description": "ZAELIG Hotel in Knokke-Heist. De naam zegt het zelf: hier beleef je echt een zaelig verblijf! Dit hotel in de polders is een droom voor hondenbaasjes. Terwijl jij…",
    "image": "https://hondaanzee.be/zaelig.webp",
    "imageAlt": "ZAELIG Hotel in Knokke-Heist | HondAanZee.be"
  },
  "/de-panne/hotspots/restaurant-imperial": {
    "title": "Restaurant Imperial in De Panne | HondAanZee.be",
    "description": "Restaurant Imperial in De Panne. In een hip en vernieuwd interieur introduceert Imperial een gezellig foodsharing concept. Ideaal om samen te proeven van tapas…",
    "image": "https://hondaanzee.be/imperial.webp",
    "imageAlt": "Restaurant Imperial in De Panne | HondAanZee.be"
  },
  "/zeebrugge/hotspots/club-north-by-icarus": {
    "title": "Club North by Icarus in Zeebrugge | HondAanZee.be",
    "description": "Club North by Icarus in Zeebrugge. Dé ultieme surfclub aan de rand van de Blankenbergse duinen waar honden het hele jaar door welkom zijn – zowel op het strand als…",
    "image": "https://hondaanzee.be/clubnorthicarus.webp",
    "imageAlt": "Club North by Icarus in Zeebrugge | HondAanZee.be"
  },
  "/middelkerke/hotspots/zina-s-place": {
    "title": "Zina's Place in Middelkerke - Westende | HondAanZee.be",
    "description": "Zina's Place in Middelkerke - Westende. Op zoek naar een vakantiehuisje waar je met meerdere honden welkom bent? Zina's Place, een charmant vissershuisje in…",
    "image": "https://hondaanzee.be/zinasplace.webp",
    "imageAlt": "Zina's Place in Middelkerke - Westende | HondAanZee.be"
  },
  "/blankenberge/hotspots/new-poseidon": {
    "title": "New Poseidon in Blankenberge | HondAanZee.be",
    "description": "New Poseidon in Blankenberge. Toegankelijke brasserie vlak bij zee waar dagverse producten, een losse sfeer en een warme ontvangst mooi samenkomen.",
    "image": "https://hondaanzee.be/newposeidon.webp",
    "imageAlt": "New Poseidon in Blankenberge | HondAanZee.be"
  },
  "/oostende/hotspots/de-zeegeuzen": {
    "title": "De Zeegeuzen in Oostende | HondAanZee.be",
    "description": "De Zeegeuzen in Oostende. Traditioneel café vlak bij de visserskaai met een nautische toets, een stevige bierkaart en genoeg eigenheid om meer te zijn dan zomaar…",
    "image": "https://hondaanzee.be/zeegeuzen2.webp",
    "imageAlt": "De Zeegeuzen in Oostende | HondAanZee.be"
  },
  "/oostende/hotspots/t-waterhuis": {
    "title": "'t Waterhuis in Oostende | HondAanZee.be",
    "description": "'t Waterhuis in Oostende. Bekende brasserie in Oostende waar honden met open armen worden ontvangen en je van lunch tot late avond terechtkunt.",
    "image": "https://hondaanzee.be/waterhuis.jpg",
    "imageAlt": "'t Waterhuis in Oostende | HondAanZee.be"
  },
  "/knokke-heist/hotspots/ijssalon-tearoom-zeebries": {
    "title": "IJssalon/Tearoom Zeebries in Knokke-Heist | HondAanZee.be",
    "description": "IJssalon/Tearoom Zeebries in Knokke-Heist. Pure passie en vakmanschap in elke hap en elke slok! Al 40 jaar draait deze gedreven eigenaar zelf het allerlekkerste…",
    "image": "https://hondaanzee.be/zeebriesfinal.webp",
    "imageAlt": "IJssalon/Tearoom Zeebries in Knokke-Heist | HondAanZee.be"
  },
  "/blankenberge/hotspots/brasserie-montmartre": {
    "title": "Brasserie Montmartre in Blankenberge | HondAanZee.be",
    "description": "Brasserie Montmartre in Blankenberge. Ruime brasserie op de Zeedijk waar gezinnen met honden graag gezien zijn.",
    "image": "https://hondaanzee.be/brasseriemontmatreblankenberge.webp",
    "imageAlt": "Brasserie Montmartre in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/bel-air": {
    "title": "Bel'air in Blankenberge | HondAanZee.be",
    "description": "Bel'air in Blankenberge. Charmant restaurant op de Zeedijk waar gastronomie en een warme sfeer hand in hand gaan. Jouw viervoeter is hier van harte welkom om mee…",
    "image": "https://hondaanzee.be/belairv2.webp",
    "imageAlt": "Bel'air in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/beach-palace-hotel": {
    "title": "Beach Palace Hotel in Blankenberge | HondAanZee.be",
    "description": "Beach Palace Hotel in Blankenberge. Luxueus 5-sterren hotel direct aan de Zeedijk met 20 prachtig uitgeruste kamers speciaal ingericht voor gasten met honden…",
    "image": "https://hondaanzee.be/beachpalace.webp",
    "imageAlt": "Beach Palace Hotel in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/seascape-penthouse": {
    "title": "Seascape Penthouse in Blankenberge | HondAanZee.be",
    "description": "Seascape Penthouse in Blankenberge. Stijlvol penthouse op de zeedijk met panoramisch zeezicht en een privé dakterras voor wie van een verblijf zelf al een…",
    "image": "https://hondaanzee.be/seascapeV4.webp",
    "imageAlt": "Seascape Penthouse in Blankenberge | HondAanZee.be"
  },
  "/koksijde/hotspots/boutique-hotel-ter-duinen": {
    "title": "Boutique-Hotel ter Duinen in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Boutique-Hotel ter Duinen in Koksijde - Oostduinkerke. Sfeervol luxe boutique-hotel in Oostduinkerke-Bad waar honden oprecht van harte welkom zijn. Wat dit hotel…",
    "image": "https://hondaanzee.be/hofterduinen.webp",
    "imageAlt": "Boutique-Hotel ter Duinen in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/hotel-apostroff": {
    "title": "Hotel Apostroff in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Hotel Apostroff in Koksijde - Oostduinkerke. Modern en populair hotel in Koksijde waar viervoeters véél meer zijn dan louter 'getolereerd'. Het team ontvangt…",
    "image": "https://hondaanzee.be/apostroff.webp",
    "imageAlt": "Hotel Apostroff in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/hotel-lehouck": {
    "title": "Hotel Lehouck in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Hotel Lehouck in Koksijde - Oostduinkerke. Charmant, familiaal gerund hotel in Koksijde dat er écht om bekend staat extreem gastvrij te zijn voor honden en hun…",
    "image": "https://hondaanzee.be/lehouck.webp",
    "imageAlt": "Hotel Lehouck in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/casino-hotel": {
    "title": "Casino Hotel in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Casino Hotel in Koksijde - Oostduinkerke. Luxueus en prachtig gelegen hotel in het centrum van Koksijde dat absoluut geen drempel vormt voor hondeneigenaars…",
    "image": "https://hondaanzee.be/casinohotel.webp",
    "imageAlt": "Casino Hotel in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/hotel-domein-westhoek": {
    "title": "Hotel Domein Westhoek in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Hotel Domein Westhoek in Koksijde - Oostduinkerke. Rustig gelegen hotel op een uitgestrekt domein midden in het groen van de duinen in Oostduinkerke. De perfecte…",
    "image": "https://hondaanzee.be/domeinwesthoek.webp",
    "imageAlt": "Hotel Domein Westhoek in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/bistronomie-eglantier": {
    "title": "Bistronomie Eglantier in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Bistronomie Eglantier in Koksijde - Oostduinkerke. Trendy en verfijnd bistro verbonden aan Boutique-Hotel ter Duinen, waar gastronomisch eten gelukkig niet…",
    "image": "https://hondaanzee.be/eglantier.webp",
    "imageAlt": "Bistronomie Eglantier in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/restaurant-akote": {
    "title": "Restaurant Akoté in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Restaurant Akoté in Koksijde - Oostduinkerke. Hip en jong restaurant verbonden aan Hotel Apostroff, met een menu vol verse en seizoensgebonden gerechten. Niet…",
    "image": "https://hondaanzee.be/akote.webp",
    "imageAlt": "Restaurant Akoté in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/de-spelleplekke": {
    "title": "De Spelleplekke in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "De Spelleplekke in Koksijde - Oostduinkerke. Waanzinnig gezellige en jonge plek in Oostduinkerke voor een smakelijke lunch, een ontspannen diner of een relaxte…",
    "image": "https://hondaanzee.be/spelleplekke.webp",
    "imageAlt": "De Spelleplekke in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/t-zoet-genot": {
    "title": "'t Zoet Genot in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "'t Zoet Genot in Koksijde - Oostduinkerke. De absolute hotspot op de Zeedijk van Oostduinkerke voor een fantastische koffie, ambachtelijke pannenkoeken of een…",
    "image": "https://hondaanzee.be/zoetgenot.webp",
    "imageAlt": "'t Zoet Genot in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/tearoom-t-zand": {
    "title": "Tearoom 't Zand in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Tearoom 't Zand in Koksijde - Oostduinkerke. Vertrouwde tearoom op de Zeedijk, gekend om hun huisgemaakte garnaalkroketten en ontspannen sfeer. Het team is oprecht…",
    "image": "https://hondaanzee.be/tzand.webp",
    "imageAlt": "Tearoom 't Zand in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/de-clochard": {
    "title": "De Clochard in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "De Clochard in Koksijde - Oostduinkerke. Authentieke grillzaak met een warm en huiselijk karakter die al jaren een vaste kustwaarde is. Honden zijn hier standaard…",
    "image": "https://hondaanzee.be/clochard.webp",
    "imageAlt": "De Clochard in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/koffiebar-cafelito": {
    "title": "Koffiebar Cafelito in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Koffiebar Cafelito in Koksijde - Oostduinkerke. Een enorm sfeervolle koffiebar op de Zeelaan waar jij en je hond beiden van harte welkom zijn. Terwijl jij geniet…",
    "image": "https://hondaanzee.be/cafelito.webp",
    "imageAlt": "Koffiebar Cafelito in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/tearoom-chopin": {
    "title": "Tearoom Chopin in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Tearoom Chopin in Koksijde - Oostduinkerke. Een klassieker in Koksijde: een verzorgde en populaire tearoom die er bewust voor kiest honden met open armen te…",
    "image": "https://hondaanzee.be/chopin.webp",
    "imageAlt": "Tearoom Chopin in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/bistro-t-fornhuis": {
    "title": "Bistro 't Fornhuis in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Bistro 't Fornhuis in Koksijde - Oostduinkerke. Een enorm gezellige, lokale bistro verscholen in Oostduinkerke, ver van het toeristisch gewoel van de dijk. Hier…",
    "image": "https://hondaanzee.be/fornhuis.webp",
    "imageAlt": "Bistro 't Fornhuis in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/happy-times": {
    "title": "Happy Times in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Happy Times in Koksijde - Oostduinkerke. Een heerlijk informele plek voor huisgemaakte burgers, tapas en fish & chips, ondergebracht in een uniek en eigenzinnig…",
    "image": "https://hondaanzee.be/happytimes.webp",
    "imageAlt": "Happy Times in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/eethuis-t-blekkertje": {
    "title": "Eethuis 't Blekkertje in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Eethuis 't Blekkertje in Koksijde - Oostduinkerke. Genieten van (h)eerlijke, huisbereide klassiekers in een warme sfeer? Bij 't Blekkertje leggen chef Steve en…",
    "image": "https://hondaanzee.be/blekker.webp",
    "imageAlt": "Eethuis 't Blekkertje in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/restaurant-lehouck": {
    "title": "Restaurant Lehouck in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Restaurant Lehouck in Koksijde - Oostduinkerke. Een culinaire parel waar Franse verfijning en hondvriendelijkheid hand in hand gaan. Het uitgebreide menu biedt een…",
    "image": "https://hondaanzee.be/lehouck_restaurant.webp",
    "imageAlt": "Restaurant Lehouck in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/in-t-dorp": {
    "title": "In 't Dorp in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "In 't Dorp in Koksijde - Oostduinkerke. Zin in een avondje uit waar jouw viervoeter écht welkom is? Bij In 't Dorp vind je de ideale, gezellige plek voor een…",
    "image": "https://hondaanzee.be/dorp2.webp",
    "imageAlt": "In 't Dorp in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/de-panne/hotspots/agora-bar-food-drinks": {
    "title": "Agora Bar Food & Drinks in De Panne | HondAanZee.be",
    "description": "Agora Bar Food & Drinks in De Panne. De perfecte hondvriendelijke pitstop in hartje De Panne! Strijk neer op het grote, zonnige terras op de Markt voor een…",
    "image": "https://hondaanzee.be/agora2.webp",
    "imageAlt": "Agora Bar Food & Drinks in De Panne | HondAanZee.be"
  },
  "/koksijde/hotspots/d-appeti-jt": {
    "title": "d'Appeti(jt) in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "d'Appeti(jt) in Koksijde - Oostduinkerke. Een heerlijk koffie- en eethuis met een enorm groot hart voor honden! De gastvrije uitbaters hebben zelf een superleuke…",
    "image": "https://hondaanzee.be/appetit.webp",
    "imageAlt": "d'Appeti(jt) in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/koffiebar-kantine": {
    "title": "Koffiebar Kantine in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Koffiebar Kantine in Koksijde - Oostduinkerke. Een gezellige koffiebar waar je in een ontspannen sfeer kunt genieten van heerlijke koffie en verse versnaperingen…",
    "image": "https://hondaanzee.be/kantine.webp",
    "imageAlt": "Koffiebar Kantine in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/visrestaurant-ode": {
    "title": "Visrestaurant Odé in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Visrestaurant Odé in Koksijde - Oostduinkerke. Het enige visrestaurant in Oostduinkerke, gerund door de gepassioneerde eigenaar John die ook een viswinkel uitbaat…",
    "image": "https://hondaanzee.be/ode.webp",
    "imageAlt": "Visrestaurant Odé in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/hotspots/brasserie-de-barkentijn": {
    "title": "Brasserie De Barkentijn in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Brasserie De Barkentijn in Koksijde - Oostduinkerke. Bij strandrestaurant - tearoom De Barkentijn is het iedere dag genieten van het prachtige uitzicht. Ook bij…",
    "image": "https://hondaanzee.be/barkentijn2.webp",
    "imageAlt": "Brasserie De Barkentijn in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/blankenberge/hotspots/skateshop-daily-grind": {
    "title": "Skateshop Daily Grind in Blankenberge | HondAanZee.be",
    "description": "Skateshop Daily Grind in Blankenberge. Skateshop met een eigen stijl, sterke selectie boards en streetwear, en een opvallend warme ontvangst voor honden.",
    "image": "https://hondaanzee.be/dailygrind.webp",
    "imageAlt": "Skateshop Daily Grind in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/restaurant-koekie-s": {
    "title": "Restaurant Koekie's in Blankenberge | HondAanZee.be",
    "description": "Restaurant Koekie's in Blankenberge. Sfeervol restaurant vlak bij haven en strand waar je terechtkunt voor sterke klassiekers zoals ribbetjes en huisgemaakte…",
    "image": "https://hondaanzee.be/koekies1.png",
    "imageAlt": "Restaurant Koekie's in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/brasserie-cappuccino": {
    "title": "Brasserie Cappuccino in Blankenberge | HondAanZee.be",
    "description": "Brasserie Cappuccino in Blankenberge. Een trendy brasserie met een prachtig zeezicht op de Zeedijk van Blankenberge! Brasserie Cappuccino zet in op een…",
    "image": "https://hondaanzee.be/cappuccino2.webp",
    "imageAlt": "Brasserie Cappuccino in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/two-for-you-crystals-and-gifts": {
    "title": "Two For You - Crystals and Gifts in Blankenberge | HondAanZee.be",
    "description": "Two For You - Crystals and Gifts in Blankenberge. Sfeervolle winkel in Blankenberge met edelstenen, mineralen en spirituele cadeaus, gedragen door een heel…",
    "image": "https://hondaanzee.be/twoforyou.webp",
    "imageAlt": "Two For You - Crystals and Gifts in Blankenberge | HondAanZee.be"
  },
  "/de-haan/hotspots/brasserie-la-potiniere": {
    "title": "Brasserie La Potinière in De Haan | HondAanZee.be",
    "description": "Brasserie La Potinière in De Haan. Sfeervolle brasserie met uitzicht over het prachtige parkdomein van De Haan — dé plek om te ontspannen met je viervoeter na een…",
    "image": "https://hondaanzee.be/poti1.webp",
    "imageAlt": "Brasserie La Potinière in De Haan | HondAanZee.be"
  },
  "/blankenberge/hotspots/abc-hotel": {
    "title": "ABC Hotel in Blankenberge | HondAanZee.be",
    "description": "ABC Hotel in Blankenberge. Kleinschalig viersterren eco-hotel in Blankenberge waar design, persoonlijke service en een hondvriendelijk verblijf mooi samenkomen.",
    "image": "https://hondaanzee.be/abchotel.webp",
    "imageAlt": "ABC Hotel in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/au-pengouin": {
    "title": "Au Pengouin in Blankenberge | HondAanZee.be",
    "description": "Au Pengouin in Blankenberge. Klassieke zaak in het centrum van Blankenberge die vooral bekendstaat om royale wafels, verse pannenkoeken en een vlotte bediening.",
    "image": "https://hondaanzee.be/pengouin.webp",
    "imageAlt": "Au Pengouin in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/hotspots/beachclub-blankenberge": {
    "title": "Beachclub Blankenberge in Blankenberge | HondAanZee.be",
    "description": "Beachclub Blankenberge in Blankenberge. Beachclub Blankenberge is dé perfecte stop op de Zeedijk voor hondenbaasjes! Vanaf hier tot en met Zeebrugge mogen honden…",
    "image": "https://hondaanzee.be/beachclub.webp",
    "imageAlt": "Beachclub Blankenberge in Blankenberge | HondAanZee.be"
  },
  "/oostende/hotspots/brassi-beach-terrace": {
    "title": "Brassi Beach Terrace in Oostende | HondAanZee.be",
    "description": "Brassi Beach Terrace in Oostende. Brassi Beach Terrace is een hondvriendelijk terras pal aan de Albert I-promenade in Oostende, met een onverslaanbaar zicht op…",
    "image": "https://hondaanzee.be/brassi1.jpeg",
    "imageAlt": "Brassi Beach Terrace in Oostende | HondAanZee.be"
  },
  "/blankenberge/hotspots/riva-boutique": {
    "title": "Riva Boutique in Blankenberge | HondAanZee.be",
    "description": "Riva Boutique in Blankenberge. Stijlvolle modeboetiek in hartje Blankenberge waar hondjes en hun baasjes met opvallend veel warmte worden ontvangen.",
    "image": "https://hondaanzee.be/Riva.webp",
    "imageAlt": "Riva Boutique in Blankenberge | HondAanZee.be"
  },
  "/oostende/diensten/dierenarts-frederik-galle": {
    "title": "Dierenarts Frederik Galle in Oostende | HondAanZee.be",
    "description": "Dierenarts Frederik Galle in Oostende. Moderne dierenartsenpraktijk waar persoonlijke aanpak en het welzijn van uw huisdier centraal staan.",
    "image": "https://hondaanzee.be/dierenartsfredericgalle.webp",
    "imageAlt": "Dierenarts Frederik Galle in Oostende | HondAanZee.be"
  },
  "/oostende/diensten/dier-tuincenter-rommel": {
    "title": "Dier & Tuincenter Rommel in Oostende | HondAanZee.be",
    "description": "Dier & Tuincenter Rommel in Oostende. Familiezaak met meer dan 20 jaar ervaring en een enorm aanbod aan voeding en accessoires.",
    "image": "https://hondaanzee.be/diertuincenterrommel.webp",
    "imageAlt": "Dier & Tuincenter Rommel in Oostende | HondAanZee.be"
  },
  "/knokke-heist/diensten/dierenarts-ilse-kerckhof": {
    "title": "Dierenarts Ilse Kerckhof in Knokke-Heist | HondAanZee.be",
    "description": "Dierenarts Ilse Kerckhof in Knokke-Heist. Professionele praktijk in Westkapelle met een groot hart voor honden en katten.",
    "image": "https://hondaanzee.be/dierenartsilsekerckhof.webp",
    "imageAlt": "Dierenarts Ilse Kerckhof in Knokke-Heist | HondAanZee.be"
  },
  "/knokke-heist/diensten/dierenplezier-heist": {
    "title": "Dierenplezier Heist in Knokke-Heist | HondAanZee.be",
    "description": "Dierenplezier Heist in Knokke-Heist. Gezellige dierenwinkel waar u deskundig advies krijgt en uw hond mee mag komen shoppen.",
    "image": "https://hondaanzee.be/dierenplezierheist.webp",
    "imageAlt": "Dierenplezier Heist in Knokke-Heist | HondAanZee.be"
  },
  "/blankenberge/diensten/de-praktijk-227": {
    "title": "De Praktijk 227 in Blankenberge | HondAanZee.be",
    "description": "De Praktijk 227 in Blankenberge. Moderne dierenartsenpraktijk met ruime openingsuren en aandacht voor elk huisdier.",
    "image": "https://hondaanzee.be/praktijk227.webp",
    "imageAlt": "De Praktijk 227 in Blankenberge | HondAanZee.be"
  },
  "/blankenberge/diensten/snuffels": {
    "title": "Snuffels in Blankenberge | HondAanZee.be",
    "description": "Snuffels in Blankenberge. Honden- en kattenspeciaalzaak met een ruim aanbod aan buggy's, draagtasjes en kledij. Daarnaast vind je hier een uitgebreide collectie…",
    "image": "https://hondaanzee.be/snuffels.webp",
    "imageAlt": "Snuffels in Blankenberge | HondAanZee.be"
  },
  "/de-panne/diensten/de-dierendokter-alex-salomez": {
    "title": "De Dierendokter (Alex Salomez) in De Panne | HondAanZee.be",
    "description": "De Dierendokter (Alex Salomez) in De Panne. Ervaren dierenarts die ook 'Cat Friendly' gecertificeerd is, maar honden met open armen ontvangt.",
    "image": "https://hondaanzee.be/dedierendokter.webp",
    "imageAlt": "De Dierendokter (Alex Salomez) in De Panne | HondAanZee.be"
  },
  "/nieuwpoort/diensten/dierenarts-elise-buyse": {
    "title": "Dierenarts Elise Buyse in Nieuwpoort | HondAanZee.be",
    "description": "Dierenarts Elise Buyse in Nieuwpoort. Betrokken dierenarts in het centrum van Nieuwpoort, gespecialiseerd in kleine huisdieren.",
    "image": "https://hondaanzee.be/dierenartselisebuyse.webp",
    "imageAlt": "Dierenarts Elise Buyse in Nieuwpoort | HondAanZee.be"
  },
  "/middelkerke/diensten/dierenartsenpraktijk-katty": {
    "title": "Dierenartsenpraktijk Katty in Middelkerke - Westende | HondAanZee.be",
    "description": "Dierenartsenpraktijk Katty in Middelkerke - Westende. Warme praktijk waar uw hond de beste medische zorgen krijgt in een rustige omgeving.",
    "image": "https://hondaanzee.be/dierenartsenpraktijkkatty.webp",
    "imageAlt": "Dierenartsenpraktijk Katty in Middelkerke - Westende | HondAanZee.be"
  },
  "/middelkerke/diensten/dogs-co": {
    "title": "Dogs & Co in Middelkerke - Westende | HondAanZee.be",
    "description": "Dogs & Co in Middelkerke - Westende. Bij Dogs & Co vind je het beste van twee werelden onder één dak: De Winkel: Een stijlvolle shop met topproducten voor honden…",
    "image": "https://hondaanzee.be/dogsandco2.webp",
    "imageAlt": "Dogs & Co in Middelkerke - Westende | HondAanZee.be"
  },
  "/de-haan/diensten/dierenartsenpraktijk-breemersch": {
    "title": "Dierenartsenpraktijk Breemersch in De Haan | HondAanZee.be",
    "description": "Dierenartsenpraktijk Breemersch in De Haan. Goed uitgeruste praktijk waar een persoonlijke band met dier en eigenaar voorop staat.",
    "image": "https://hondaanzee.be/dierenartsenpraktijkbreemersch.webp",
    "imageAlt": "Dierenartsenpraktijk Breemersch in De Haan | HondAanZee.be"
  },
  "/de-haan/diensten/happy-dog": {
    "title": "Happy Dog in De Haan | HondAanZee.be",
    "description": "Happy Dog in De Haan. Hondentrimsalon dat ook voeding en verzorgingsproducten verkoopt in het centrum.",
    "image": "https://hondaanzee.be/happydog.webp",
    "imageAlt": "Happy Dog in De Haan | HondAanZee.be"
  },
  "/blankenberge/diensten/dogs-cats": {
    "title": "Dogs & Cats in Blankenberge | HondAanZee.be",
    "description": "Dogs & Cats in Blankenberge. Complete dierenwinkel voor honden en katten met voeding, accessoires en verzorgingsproducten van topkwaliteit.",
    "image": "https://hondaanzee.be/dogsandcats.webp",
    "imageAlt": "Dogs & Cats in Blankenberge | HondAanZee.be"
  },
  "/bredene/diensten/q-ties": {
    "title": "Q-ties in Bredene | HondAanZee.be",
    "description": "Q-ties in Bredene. Gespecialiseerde hondenwinkel met een breed assortiment aan kwaliteitsvoeding, speelgoed en accessoires voor je trouwe viervoeter. Deskundig…",
    "image": "https://hondaanzee.be/q-ties.webp",
    "imageAlt": "Q-ties in Bredene | HondAanZee.be"
  },
  "/oostende/diensten/dierenkliniek-anicura": {
    "title": "Dierenkliniek AniCura in Oostende | HondAanZee.be",
    "description": "Dierenkliniek AniCura in Oostende. Moderne spoedkliniek nabij Oostende, dagelijks bereikbaar van 7.30u tot 21.00u. Professionele zorg voor je huisdier wanneer je…",
    "image": "https://hondaanzee.be/anicura.webp",
    "imageAlt": "Dierenkliniek AniCura in Oostende | HondAanZee.be"
  },
  "/blankenberge/diensten/dierenarts-vanhee-s": {
    "title": "Dierenarts Vanhee S. in Blankenberge | HondAanZee.be",
    "description": "Dierenarts Vanhee S. in Blankenberge. Warme praktijk voor kleine huisdieren waar persoonlijke zorg en vertrouwen centraal staan. Dankzij moderne apparatuur en…",
    "image": "https://hondaanzee.be/dierenartsvanhee.webp",
    "imageAlt": "Dierenarts Vanhee S. in Blankenberge | HondAanZee.be"
  },
  "/de-panne/diensten/panimalia-trimsalon-hondenboetiek": {
    "title": "Panimalia Trimsalon & Hondenboetiek in De Panne | HondAanZee.be",
    "description": "Panimalia Trimsalon & Hondenboetiek in De Panne. Panimalia is een gepassioneerde hondenboetiek en trimsalon in het hart van De Panne, pal op de Markt. Hier draait…",
    "image": "https://hondaanzee.be/panimalia.webp",
    "imageAlt": "Panimalia Trimsalon & Hondenboetiek in De Panne | HondAanZee.be"
  },
  "/de-panne/diensten/famiflora-de-panne": {
    "title": "Famiflora De Panne in De Panne | HondAanZee.be",
    "description": "Famiflora De Panne in De Panne. Famiflora is het grootste tuin- en decoratiecenter van België en de vestiging in De Panne beschikt over een uitgebreide…",
    "image": "https://hondaanzee.be/famiflora.webp",
    "imageAlt": "Famiflora De Panne in De Panne | HondAanZee.be"
  },
  "/de-panne/diensten/dierenarts-johan-devloo": {
    "title": "Dierenarts Johan Devloo in De Panne | HondAanZee.be",
    "description": "Dierenarts Johan Devloo in De Panne. Derde generatie dierenarts met een hart van goud voor viervoeters. Sinds 1985 runt Johan Devloo zijn privépraktijk voor kleine…",
    "image": "https://hondaanzee.be/devloo2.webp",
    "imageAlt": "Dierenarts Johan Devloo in De Panne | HondAanZee.be"
  },
  "/koksijde/diensten/bazouf": {
    "title": "Bazouf in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Bazouf in Koksijde - Oostduinkerke. Bij Bazouf, de charmante dierenwinkel van eigenaars Véronique en Robine in Koksijde, draait alles om het welzijn van jouw…",
    "image": "https://hondaanzee.be/bazouf.webp",
    "imageAlt": "Bazouf in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/diensten/vets-for-pets": {
    "title": "Vets For Pets in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Vets For Pets in Koksijde - Oostduinkerke. Vets For Pets is een moderne en toegankelijke dierenartsenpraktijk in Koksijde waar het welzijn van jouw hond centraal…",
    "image": "https://hondaanzee.be/vetsforpets.webp",
    "imageAlt": "Vets For Pets in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/diensten/dierenartsencentrum-anoa": {
    "title": "Dierenartsencentrum Anoa in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Dierenartsencentrum Anoa in Koksijde - Oostduinkerke. Dierenartsencentrum Anoa combineert echte passie voor dieren met topkwaliteit diergeneeskunde. Dankzij het…",
    "image": "https://hondaanzee.be/anoa.webp",
    "imageAlt": "Dierenartsencentrum Anoa in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/diensten/dierenarts-debakker-olivier": {
    "title": "Dierenarts Debakker Olivier in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Dierenarts Debakker Olivier in Koksijde - Oostduinkerke. Olivier Debakker is een dierenarts met meer dan dertig jaar praktijkervaring — opgegroeid met paarden en…",
    "image": "https://hondaanzee.be/olivierdebakker.webp",
    "imageAlt": "Dierenarts Debakker Olivier in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/koksijde/diensten/dierenartsencentrum-clos-fleuri": {
    "title": "Dierenartsencentrum Clos Fleuri in Koksijde - Oostduinkerke | HondAanZee.be",
    "description": "Dierenartsencentrum Clos Fleuri in Koksijde - Oostduinkerke. Dierenartsencentrum Clos Fleuri in Koksijde werkt uitsluitend op afspraak — zo krijgt elk dier de…",
    "image": "https://hondaanzee.be/fleuri.webp",
    "imageAlt": "Dierenartsencentrum Clos Fleuri in Koksijde - Oostduinkerke | HondAanZee.be"
  },
  "/agenda/kwispelfestival-de-panne-2026": {
    "title": "Kwispelfestival De Panne | Agenda HondAanZee.be",
    "description": "Maak je klaar voor dé dag van het jaar waar jouw viervoeter de absolute ster is! Op het Kwispelfestival in De Panne draait alles om plezier, avontuur en heel veel kwispelende staartjes. Geniet samen van een prachtige wandeltocht langs de kust, ontdek leuke workshops waar je hond nieuwe tricks leert, en laat een professionele foto maken als aandenken. Terwijl jouw trouwe metgezel zich uitleeft, kun jij gezellig rondsnuffelen op de gezellige hondenmarkt vol leuke spulletjes, of kijk je ogen uit bij spectaculaire demonstraties. Een dag vol beleving, ontmoeting en onvergetelijke momenten — voor honden én hun baasjes!",
    "image": "https://hondaanzee.be/kwispelfestival.webp"
  },
  "/agenda/groot-oostends-hondenfestival-2026": {
    "title": "Groot Oostends Hondenfestival | Agenda HondAanZee.be",
    "description": "Na het overweldigende succes van de eerste editie in 2025 keert het Groot Oostends Hondenfestival terug — en dit keer nog groter. Op zaterdag 23 en zondag 24 mei 2026 verandert Domein Duin & Zee opnieuw in een hondenparadijs van 12.000 m² vol demonstraties, standhouders, losloopplezier en food corners voor mens en dier. Nieuw dit jaar is de grote Stratier-hondenwandeling ten voordele van dierenasielen: beide dagen vertrekt die om 11:00 aan de Stratier-stand op het festivalterrein. Zo combineer je een gratis festivaldag aan zee met een extra wandeling die niet alleen leuk is, maar ook adoptie en asieldieren extra in de kijker zet.",
    "image": "https://hondaanzee.be/oostendshondenfestival.webp"
  },
  "/agenda/grote-hondenwandeling-bredene-2026": {
    "title": "Grote Hondenwandeling Bredene | Agenda HondAanZee.be",
    "description": "De zee, het strand en de Bredense duinen vormen opnieuw het decor voor de jaarlijkse Grote Hondenwandeling! Vanaf 11 uur vertrek je aan het Jeugdhuis Creatuur en volg je de pijltjes doorheen het Bredense groen, de duinen en langs het strand. De bewegwijzering brengt je heen en terug samen met je favoriete viervoeter(s). Bij aankomst wacht er een superleuke attentie voor je beste vriend! Speciaal voor de oudere deelnemers is er opnieuw een verkorte route voorzien — zodat elke hond mee kan genieten van deze fantastische dag.",
    "image": "https://hondaanzee.be/hondenbredene.webp"
  },
  "/losloopzones/blankenberge-vande-puttelaan": {
    "title": "Hondenweide J. Vande Puttelaan | Losloopzones HondAanZee.be",
    "description": "Omheinde hondenweide op het grasveld tussen Oude Steenweg en J. Vande Puttelaan.",
    "image": "https://hondaanzee.be/vandeputtelaan.webp"
  },
  "/losloopzones/blankenberge-van-ackersquare": {
    "title": "Hondenweide A. Van Ackersquare | Losloopzones HondAanZee.be",
    "description": "Omheinde hondenweide op de site van het voormalige zwembad/Nordzeebad.",
    "image": "https://hondaanzee.be/noordzeebad.webp"
  },
  "/losloopzones/knokke-heist-losloopweide-heist": {
    "title": "Losloopweide Heist | Losloopzones HondAanZee.be",
    "description": "Nieuwe weide (geopend 2024) in de groene zone naast de parking en het bufferbekken.",
    "image": "https://hondaanzee.be/weideheist.webp"
  },
  "/losloopzones/de-haan-vosseslag": {
    "title": "Losloopzone Vosseslag | Losloopzones HondAanZee.be",
    "description": "Omheinde zone naast de parking.",
    "image": "https://hondaanzee.be/losloopzonevosseslag.webp"
  },
  "/losloopzones/de-haan-centrum-sport": {
    "title": "Losloopzone Centrum/Sport | Losloopzones HondAanZee.be",
    "description": "Gelegen bij Sport- en Recreatiecentrum Haneveld.",
    "image": "https://hondaanzee.be/losloopweide_sport.webp"
  },
  "/losloopzones/de-haan-haneveld": {
    "title": "Losloopzone Haneveld | Losloopzones HondAanZee.be",
    "description": "Zone nabij het sportcomplex Haneveld.",
    "image": "https://hondaanzee.be/losloopzonehaneveld.webp"
  },
  "/losloopzones/de-haan-duinbossen": {
    "title": "Losloopzone Duinbossen | Losloopzones HondAanZee.be",
    "description": "Grote omheinde boszone van 1,2 hectare. Bereikbaar via parking Zwarte Kiezel (ca. 100m wandelen).",
    "image": "https://hondaanzee.be/losloopzoneduinbossen.webp"
  },
  "/losloopzones/wenduine-manitobastraat": {
    "title": "Losloopzone Wenduine - Manitobastraat | Losloopzones HondAanZee.be",
    "description": "Omheinde hondenweide in Wenduine.",
    "image": "https://hondaanzee.be/losloopzonewenduinemanitobastraat.webp"
  },
  "/losloopzones/wenduine-westhinderlaan": {
    "title": "Losloopzone Wenduine - Westhinderlaan | Losloopzones HondAanZee.be",
    "description": "Gelegen op de hoek van Westhinderlaan en Wancourstraat.",
    "image": "https://hondaanzee.be/losloopzonewenduinewesthinderlaan.webp"
  },
  "/losloopzones/bredene-kerkstraat": {
    "title": "Hondenweide Kerkstraat | Losloopzones HondAanZee.be",
    "description": "Volledig omheind grasveld naast jeugdhuis Creatuur.",
    "image": "https://hondaanzee.be/brouwerijstraatbredene.webp"
  },
  "/losloopzones/oostende-maria-hendrikapark": {
    "title": "Maria Hendrikapark | Losloopzones HondAanZee.be",
    "description": "Grootste en populairste hondenloopweide van Oostende. De weide ligt achter het Dierenasiel \"Het Blauwe Kruis\". Niet zichtbaar vanaf de hoofdweg.",
    "image": "https://hondaanzee.be/hendrikapark.webp"
  },
  "/losloopzones/oostende-raversijde": {
    "title": "Losloopzone Raversijde | Losloopzones HondAanZee.be",
    "description": "Ruime losloopzone nabij de luchthaven en Nieuwpoortsesteenweg. Gelegen aan de rand van het Provinciedomein Raversijde, met veel open ruimte om te rennen en te spelen.",
    "image": "https://hondaanzee.be/raversijde.webp"
  },
  "/losloopzones/oostende-leffingestraat": {
    "title": "Losloopzone Leffingestraat | Losloopzones HondAanZee.be",
    "description": "Veilige, omheinde zone achter de Ostend Tennis Club. Volledig verborgen achter de tennisvelden, je moet langs het tennisgebouw kijken.",
    "image": "https://hondaanzee.be/placeholder.webp"
  },
  "/losloopzones/oostende-lijndraaiersstraat": {
    "title": "Losloopzone Lijndraaiersstraat | Losloopzones HondAanZee.be",
    "description": "Omheind stuk gras op de hoek van Stapelshuisstraat en Lijndraaiersstraat (Oosteroever). Voorheen bekend als \"Slachthuiskaai\".",
    "image": "https://hondaanzee.be/placeholder.webp"
  },
  "/losloopzones/oostende-ankerstraat": {
    "title": "Losloopzone Ankerstraat | Losloopzones HondAanZee.be",
    "description": "Smalle, langgerekte strook gras die parallel loopt aan de tramsporen. Ziet eruit als een berm, maar is omheind voor honden.",
    "image": "https://hondaanzee.be/ankerstraat.webp"
  },
  "/losloopzones/oostende-hondenbos": {
    "title": "Hondenbos | Losloopzones HondAanZee.be",
    "description": "Groot hondenbos (ca. 3,5 hectare) in natuurzone nabij de brug van de A10. Je moet de Karperstraat inrijden (doodlopend) om de toegang te vinden.",
    "image": "https://hondaanzee.be/hondenbos.webp"
  },
  "/losloopzones/oostende-brigade-pironlaan": {
    "title": "Losloopzone Brigade Pironlaan | Losloopzones HondAanZee.be",
    "description": "Praktische zone in de groene strook voor buurtbewoners. Recent vernieuwd met speeltoestellen (april 2023).",
    "image": "https://hondaanzee.be/pironlaan.webp"
  },
  "/losloopzones/oostende-provinciedomein-raversijde": {
    "title": "Provinciedomein Raversijde | Losloopzones HondAanZee.be",
    "description": "Specifieke speelweide binnen het provinciedomein (ingang via Westlaan). In de rest van het park moeten honden aan de leiband.",
    "image": "https://hondaanzee.be/provinciedomein.webp"
  },
  "/losloopzones/oostende-schorrepark": {
    "title": "Losloopweide Schorrepark | Losloopzones HondAanZee.be",
    "description": "Eén van de mooiste en grootste losloopweiden aan de kust. Dit uitgestrekte natuurgebied aan de rand van Oostende (Stene) biedt vijvers waar honden kunnen zwemmen, bunkers, heuvels en prachtige wilde bloemen. Het terrein is niet omheind maar afgelegen genoeg voor honden om voluit te lopen. Een toplocatie voor grotere rassen en honden die graag zwemmen.",
    "image": "https://hondaanzee.be/losloopweidedeschorre.webp"
  },
  "/losloopzones/middelkerke-koninginnelaan": {
    "title": "Hondenweide Middelkerke | Losloopzones HondAanZee.be",
    "description": "Gezellige, volledig omheinde hondenweide in de rustige wijk achter de Stille Meers. Een sociale plek waar je altijd wel andere baasjes en honden tegenkomt - perfect voor je viervoeter om nieuwe speelkameraadjes te maken! De veilige, afgeslotenzone ligt tegenover het Woonzorgcentrum Haerlebout. Tip: help mee om deze fijne plek proper te houden voor iedereen.",
    "image": "https://hondaanzee.be/stillemeers.webp"
  },
  "/losloopzones/middelkerke-westende": {
    "title": "Hondenweide Westende | Losloopzones HondAanZee.be",
    "description": "Rustige plek vlakbij Sportpark \"De Krokodiel\". Zoek naar de kruising met de Voetbalstraat.",
    "image": "https://hondaanzee.be/placeholder.webp"
  },
  "/losloopzones/nieuwpoort-prins-mauritspark": {
    "title": "Hondenweide Prins Mauritspark | Losloopzones HondAanZee.be",
    "description": "Grote omheinde zone (ca. 2.500 m┬▓) aan de kant van de havengeul, vlakbij het vakantiepark. Uitstekend alternatief voor het strand in de zomer!",
    "image": "https://hondaanzee.be/placeholder.webp"
  },
  "/losloopzones/nieuwpoort-leopold-ii-park": {
    "title": "Hondenweide Leopold II Park | Losloopzones HondAanZee.be",
    "description": "Kleinere omheinde zone binnenin het park, voorzien van een saskluis bij de ingang.",
    "image": "https://hondaanzee.be/placeholder.webp"
  },
  "/losloopzones/koksijde-sportpark-oostduinkerke": {
    "title": "Losloopzone Sportpark Oostduinkerke | Losloopzones HondAanZee.be",
    "description": "Ruime zone aan de rand van sportcomplex \"Hazebeek\".",
    "image": "https://hondaanzee.be/placeholder.webp"
  },
  "/losloopzones/koksijde-ster-der-zee": {
    "title": "Losloopzone Koksijde Ster Der Zee | Losloopzones HondAanZee.be",
    "description": "Hondenspeelzone nabij het Abdijmuseum Ten Duinen. Ingang via de Gladiolenlaan.",
    "image": "https://hondaanzee.be/losloopzonekoksijdesterderzee.webp"
  },
  "/losloopzones/de-panne-kerkstraat": {
    "title": "Hondenweide Kerkstraat | Losloopzones HondAanZee.be",
    "description": "Belangrijkste omheinde losloopweide in De Panne. Je moet helemaal naar achteren, naast de begraafplaats en motorclub \"t Motosiekeltje\".",
    "image": "https://hondaanzee.be/placeholder.webp"
  },
  "/losloopzones/adinkerke-doornstraat": {
    "title": "Hondenweide Doornstraat | Losloopzones HondAanZee.be",
    "description": "Ruime omheinde hondenlosloopzone op het domein van Vijvers Markey, ook bereikbaar via de Moersesteenweg. De weide heeft twee ingangen en is heuvelachtig aangelegd. Er kan langs de weg geparkeerd worden. Een hondentoilet ligt op ongeveer 30 meter van de losloopzone. Zitbank aanwezig.",
    "image": "https://hondaanzee.be/weidedoornstraat.webp"
  }
};
