// AUTO-GENERATED BY scripts/generate-og-data.cjs
export default {
  "/": {
    "title": "Honden aan Zee België 2026 | Strandregels, Losloopzones & Hondvriendelijke Plekken aan de Belgische Kust",
    "description": "✓ Actuele strandregels voor honden ✓ Losloopzones en hondenweides ✓ Hondvriendelijke cafés, restaurants & hotels ✓ Alle badsteden van De Panne tot Knokke ✓ Gratis & up-to-date info 2026",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/blog": {
    "title": "Blog | HondAanZee.be — Tips, Natuur & Nieuws over Honden aan de Belgische Kust",
    "description": "Lees onze blogs over honden aan de Belgische kust: van zeehonden op het strand tot opruimacties. Nuttige info, tips en achtergronden voor elke hondenbezitter.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/hotspots": {
    "title": "Hondvriendelijke Hotspots Belgische Kust | Cafés, Restaurants, Hotels & Winkels waar Honden Welkom Zijn",
    "description": "Ontdek de beste hondvriendelijke cafés, restaurants, hotels en winkels aan de Belgische kust. Van Oostende tot Knokke - waar je hond écht welkom is.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/diensten": {
    "title": "Dierenartsen & Dierenwinkels Belgische Kust | Praktische Diensten voor Hondenbezitters",
    "description": "Vind de beste dierenartsen en dierenwinkels aan de Belgische kust. Van Oostende tot Knokke - alle praktische diensten voor je hond op één plek.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/losloopzones": {
    "title": "Losloopzones Belgische Kust | Overzicht Hondenweides & Losloopgebieden aan Zee",
    "description": "Interactieve kaart met alle losloopzones en hondenweides aan de Belgische kust. Van De Panne tot Knokke.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/over-ons": {
    "title": "Over HondAanZee.be | Ons Verhaal & Missie – De Belgische Kust voor Hondenbezitters",
    "description": "Leer het team achter HondAanZee.be kennen. Onze missie: de meest complete, gratis gids voor hondeneigenaars aan de Belgische kust.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/steun-ons": {
    "title": "Steun HondAanZee.be | Trakteer ons op een Hondenkoekje 🐾",
    "description": "HondAanZee.be is 100% gratis. Steun ons werk en help ons de leukste plekken aan de Belgische kust te blijven delen voor hondenbezitters.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/agenda": {
    "title": "Hondvriendelijke Evenementen Belgische Kust 2026 | Agenda & Events – HondAanZee.be",
    "description": "Ontdek alle hondvriendelijke evenementen aan de Belgische kust in 2026: festivals, wandelingen en meer.",
    "image": "https://hondaanzee.be/kwispelfestival.webp"
  },
  "/kaart": {
    "title": "Interactieve Kaart Belgische Kust | Alle Hondvriendelijke Locaties op de Kaart – HondAanZee.be",
    "description": "Bekijk alle hondvriendelijke stranden, losloopzones, cafés, restaurants en dierenartsen op onze interactieve kaart.",
    "image": "https://hondaanzee.be/og-imagefinal.webp"
  },
  "/meldpunt": {
    "title": "Meldpunt Gif & Overlast Belgische Kust | HondAanZee.be",
    "description": "Meld verdachte stoffen, gif, afval, hondenpoep en andere overlast aan de Belgische kust.",
    "image": "https://hondaanzee.be/properstrand.webp"
  },
  "/blog/blauwalg-hond-strand-waarschuwing": {
    "title": "Doe de Water-Check: Zo Herken Je Blauwalg Voordat Je Hond Erin Zwemt Of Eruit Drinkt | HondAanZee.be Blog",
    "description": "Niets heerlijker dan je hond vrolijk het water in te zien plonzen om die opgewarmde vacht even te laten afkoelen. Maar let op voor blauwalg! Leer hier hoe je dit gevaar herkent en wat je moet doen als het misgaat.",
    "image": "https://hondaanzee.be/blauwalg.webp",
    "type": "article",
    "imageAlt": "Blauwalg in het water"
  },
  "/blog/hond-strand-warm-weer": {
    "title": "Met je hond naar zee bij warm weer: do\\ | HondAanZee.be Blog",
    "description": "Een dagje uitwaaien op het strand met je hond is heerlijk — tot de temperaturen oplopen. Honden zweten niet zoals wij en kunnen op het open zand snel oververhit raken. Met deze do\\",
    "image": "https://hondaanzee.be/OG_schaduwv1.webp",
    "type": "article",
    "imageAlt": "Hond zoekt de schaduw op tijdens een warme dag aan de Belgische kust"
  },
  "/blog/van-trekhond-tot-strandkoning-geschiedenis-kusthonden": {
    "title": "Van trekhond tot strandkoning: de vergeten geschiedenis van kusthonden | HondAanZee.be Blog",
    "description": "Lang voor honden op het strand vooral discussie opriepen over leibanden, zones en GAS-boetes, trokken ze viskarren door het zware zand. Deze vergeten kustgeschiedenis maakt je volgende wandeling met hond plots een stuk rijker.",
    "image": "https://hondaanzee.be/hondmetkar_cover.webp",
    "type": "article",
    "imageAlt": "Breed historisch coverbeeld van een trekhond met kar aan de Belgische kust"
  },
  "/blog/zeehonden-aan-de-belgische-kust": {
    "title": "Zeehonden aan de Belgische kust: wat als je hond er eentje tegenkomt? | HondAanZee.be Blog",
    "description": "Steeds vaker rusten zeehonden uit op onze Belgische stranden. Prachtig om te zien, maar wat doe je als je hond er eentje ontdekt? In deze gids lees je alles over de twee zeehondensoorten aan onze kust, wat je moet doen bij een ontmoeting, en hoe je bijdraagt aan hun bescherming.",
    "image": "https://hondaanzee.be/zeehond.webp",
    "type": "article",
    "imageAlt": "Zeehond rustend op het Belgische strand"
  },
  "/blog/opruimacties-proper-strand-lopers": {
    "title": "Opruimacties aan de kust: samen voor een proper strand | HondAanZee.be Blog",
    "description": "Elk jaar belandt er tonnen zwerfvuil op onze Belgische stranden. Gelukkig zijn er duizenden vrijwilligers die de handen uit de mouwen steken. Ontdek hoe organisaties als de Proper Strand Lopers en Mooimakers onze kust schoon houden — en hoe jij kunt meehelpen.",
    "image": "https://hondaanzee.be/properstrand.webp",
    "type": "article",
    "imageAlt": "Vrijwilligers ruimen zwerfvuil op aan het Belgische strand"
  },
  "/blog/mooiste-bossen-belgische-kust-wandelen-met-hond": {
    "title": "De 6 mooiste bossen aan de Belgische kust om te wandelen met je hond | HondAanZee.be Blog",
    "description": "De Belgische kust is veel meer dan strand en zee. Verscholen achter de duinen liggen prachtige bossen waar je heerlijk kunt wandelen met je hond. Van het historische Calmeynbos in De Panne tot het Zeebos in Blankenberge: wij zetten de 6 mooiste kustbossen op een rij — inclusief praktische info over hondenzones, wandelroutes en bereikbaarheid.",
    "image": "https://hondaanzee.be/zeebos.webp",
    "type": "article",
    "imageAlt": "Wandelpad door het Zeebos aan de Belgische kust"
  },
  "/blog/zwemplekjes-honden-belgische-kust": {
    "title": "De leukste zwemplekjes voor je hond aan de Belgische kust (en het is niet de zee!) | HondAanZee.be Blog",
    "description": "Strand en zee zijn niet de enige plekken waar je hond kan zwemmen aan de kust. Ontdek de mooiste vijvers, kreken, kanalen en waterlopen waar je viervoeter veilig en heerlijk kan afkoelen — ver weg van golven en kwallen.",
    "image": "https://hondaanzee.be/zwemhond.webp",
    "type": "article",
    "imageAlt": "Hond zwemt vrolijk in een vijver aan de Belgische kust"
  },
  "/blog/mentale-leiband-vrijheid-met-connectie": {
    "title": "De Mentale Leiband: Vrijheid door middel van Connectie en Controle | HondAanZee.be Blog",
    "description": "De Belgische kust is voor honden een zintuiglijk paradijs. Maar achter het idyllische beeld van een loslopende hond schuilt een complexe realiteit. Ontdek de filosofie van de \"mentale leiband\" en hoe je een wandeling transformeert van controle naar vertrouwen.",
    "image": "https://hondaanzee.be/OG_verantwoordelijklos.webp",
    "type": "article",
    "imageAlt": "Hond loopt los aan zee met mentale connectie - VZW Verantwoord Los"
  },
  "/blog/spiegel-aan-de-leiband-hondenpsychologie-guillaume-dervaux": {
    "title": "De Spiegel aan de Leiband: Waarom Echte Hondenliefde Begint in de Rust | HondAanZee.be Blog",
    "description": "We trainen commando\\",
    "image": "https://hondaanzee.be/OG_brunosamlulu.webp",
    "type": "article",
    "imageAlt": "Bruno, Sam en Lulu — de viervoeters achter de hondenpsychologie van Guillaume Dervaux"
  }
};
