import { reviewInput } from '../_shared/reviewInput.ts';
import { getSupabaseAdmin, getClientIp } from '../_shared/http.ts';
import { sha256 } from '../_shared/security.ts';
const origins=new Set(['https://hondaanzee.be','https://www.hondaanzee.be','http://localhost:3000','http://127.0.0.1:3000']);
Deno.serve(async req=>{
 const origin=req.headers.get('origin')||'';if(!origins.has(origin))return new Response(null,{status:403});const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':origin,'Vary':'Origin','Access-Control-Allow-Headers':'content-type,apikey,authorization,x-client-info,x-supabase-api-version,x-user-access-token','Access-Control-Allow-Methods':'POST,OPTIONS'};const send=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return send({error:'Method not allowed'},405);
 try{const raw=await req.text();if(new TextEncoder().encode(raw).length>4096)return send({error:'Te groot verzoek.'},413);const parsed=reviewInput.safeParse(JSON.parse(raw));if(!parsed.success)return send({error:'Controleer je naam, sterren en reviewtekst.'},400);const input=parsed.data;if(input.website)return send({message:'Bedankt. Je inzending wordt nagekeken.'},202);
 const db=getSupabaseAdmin(),salt=Deno.env.get('ANALYTICS_IP_SALT');if(!salt)throw new Error('Missing configuration');const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Brussels',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const fingerprint=await sha256(`reviews:${salt}:${day}:${getClientIp(req)}`);
 if(input.action==='flag'){const{error}=await db.rpc('flag_zone_review',{p_id:input.id,p_reason:input.reason,p_fingerprint:fingerprint});if(error)throw error;return send({message:'Bedankt. De beheerder kijkt je melding na.'});}
 let userId=null;const token=req.headers.get('x-user-access-token');if(token){const{data,error}=await db.auth.getUser(token);if(error||!data.user)return send({error:'Je sessie is verlopen. Meld opnieuw aan of plaats je review als gast.'},403);userId=data.user.id;}
 const{error}=await db.rpc('submit_zone_review',{p_slug:input.areaSlug,p_rating:input.rating,p_name:input.name,p_comment:input.comment,p_user_id:userId,p_fingerprint:fingerprint});if(error)throw error;return send({message:'Bedankt! Je review wacht op goedkeuring en verschijnt na controle.'},201);
 }catch(e){const m=typeof e==='object'&&e&&'message'in e?String(e.message):'';if(m.includes('RATE_LIMIT'))return send({error:'Je hebt vandaag meerdere inzendingen gedaan. Probeer morgen opnieuw.'},429);if(m.includes('DUPLICATE_REVIEW'))return send({error:'Deze review is al ontvangen.'},409);if(m.includes('INVALID_ZONE')||m.includes('REVIEW_NOT_FOUND'))return send({error:'Deze zone of review is niet meer beschikbaar.'},404);return send({error:'Je inzending kon niet worden ontvangen. Probeer opnieuw.'},500);}
});
