import { z } from 'zod';
import { getSupabaseAdmin, handleOptions, json } from '../_shared/http.ts';
import { requireAdminUser } from '../_shared/security.ts';
const cursor=z.object({date:z.iso.datetime({offset:true}),id:z.uuid()}).strict();
const schema=z.discriminatedUnion('action',[
 z.object({action:z.literal('overview')}).strict(),
 z.object({action:z.literal('list'),filter:z.enum(['all','attention','pending','published','hidden','rejected','flagged']).default('attention'),zone:z.uuid().nullable().optional(),rating:z.number().int().min(1).max(5).nullable().optional(),search:z.string().max(200).default(''),cursor:cursor.nullable().optional()}).strict(),
 z.object({action:z.literal('detail'),id:z.uuid()}).strict(),
 z.object({action:z.literal('moderate'),id:z.uuid(),version:z.number().int().positive(),decision:z.enum(['publish','hide','reject','restore','redact','note','resolve']),reason:z.string().trim().max(500).default(''),note:z.string().trim().max(2000).default(''),publicName:z.string().trim().max(50).optional(),publicComment:z.string().trim().max(500).optional()}).strict(),
]);
Deno.serve(async req=>{
 const options=handleOptions(req);if(options)return options;if(req.method!=='POST')return json({error:'Method not allowed'},405);let actor;try{actor=await requireAdminUser(req);}catch{return json({error:'Log in met je beheeraccount.'},403);}
 try{const raw=await req.text();if(new TextEncoder().encode(raw).length>16384)return json({error:'Te groot verzoek.'},413);const parsed=schema.safeParse(JSON.parse(raw));if(!parsed.success)return json({error:parsed.error.issues[0]?.message||'Controleer je verzoek.'},400);const input=parsed.data,db=getSupabaseAdmin();
 if(input.action==='overview'){const{data,error}=await db.rpc('admin_review_overview');if(error)throw error;return json(data);}
 if(input.action==='list'){const{data,error}=await db.rpc('admin_review_list',{p_filter:input.filter,p_zone:input.zone||null,p_rating:input.rating||null,p_search:input.search,p_before:input.cursor?.date||null,p_before_id:input.cursor?.id||null});if(error)throw error;return json({reviews:data});}
 if(input.action==='detail'){const{data:review,error}=await db.from('reviews').select('*').eq('id',input.id).maybeSingle();if(error)throw error;if(!review)return json({error:'Review niet gevonden.'},404);const{data:history,error:historyError}=await db.from('review_actions').select('id,actor_id,action,from_status,to_status,reason,note,created_at').eq('review_id',input.id).order('created_at',{ascending:false}).limit(100);if(historyError)throw historyError;const{data:revisions,error:revisionError}=await db.from('review_revisions').select('id,public_name,public_comment,rating,created_at').eq('review_id',input.id).order('created_at',{ascending:false}).limit(100);if(revisionError)throw revisionError;const{data:flags,error:flagError}=await db.from('review_flags').select('id,reason,created_at,resolved_at').eq('review_id',input.id).order('created_at',{ascending:false}).limit(100);if(flagError)throw flagError;const{data:zone,error:zoneError}=await db.from('content_places').select('id,city_slug,slug,draft:content_place_revisions!content_places_draft_revision_fk(content)').eq('id',review.zone_id).single();if(zoneError)throw zoneError;const{user_id,...safeReview}=review;return json({review:{...safeReview,with_account:!!user_id,zone_name:(zone.draft as any).content.name,city_slug:zone.city_slug},history:(history||[]).map(({actor_id,...entry})=>({...entry,actor_label:actor_id===actor.id?actor.email:'Beheerder'})),revisions,flags});}
 if(input.decision==='redact'&&(!input.publicName?.trim()||input.publicComment===undefined))return json({error:'Vul een publieke naam en reviewtekst in.'},400);
 const{data,error}=await db.rpc('moderate_zone_review',{p_id:input.id,p_version:input.version,p_action:input.decision,p_reason:input.reason,p_note:input.note,p_public_name:input.publicName||null,p_public_comment:input.publicComment??null,p_actor:actor.id});if(error)throw error;return json(data);
 }catch(e){const m=typeof e==='object'&&e&&'message'in e?String(e.message):'';if(m.includes('VERSION_CONFLICT'))return json({error:'Deze review is intussen beoordeeld. Vernieuw het detail voordat je verdergaat.'},409);if(m.includes('REASON_REQUIRED'))return json({error:'Geef een reden voor deze beslissing.'},400);if(m.includes('REVIEW_NOT_FOUND'))return json({error:'Review niet gevonden.'},404);return json({error:'De reviewgegevens konden niet worden verwerkt.'},500);}
});
