import type {ZoneRecord} from '../utils/adminZones.ts';
import {adminEvents,type EventRecord}from'../utils/adminEvents.ts';
type PublicationEvent=EventRecord&{kind:'event'};
type PublicationPlace=ContentPlace|ZoneRecord|PublicationEvent;
import React,{useEffect,useRef,useState}from 'react';import{Link}from 'react-router-dom';import{RefreshCw,UploadCloud,CheckCircle2,Clock}from'lucide-react';import{adminContent,adminFunction,type ContentPlace}from'../utils/adminContent.ts';
type Job={id:string;release_id:string;status:'requested'|'building'|'live'|'failed';created_at:string;live_at:string|null;error_message:string|null;deployment_url:string|null};
const statuses={requested:'Aangevraagd',building:'Website wordt gebouwd',live:'Live op productie',failed:'Mislukt'};
export default function AdminPublication(){
 const[places,setPlaces]=useState<PublicationPlace[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[jobs,setJobs]=useState<Job[]>([]),[configured,setConfigured]=useState(false),[loading,setLoading]=useState(true),[publishing,setPublishing]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const sequence=useRef(0);
 const load=async(silent=false)=>{const current=++sequence.current;if(!silent)setLoading(true);try{const[catalog,result]=await Promise.all([Promise.all([adminContent<{places:ContentPlace[]}>({action:'list'}),adminFunction<{zones:ZoneRecord[]}>('admin-zones',{action:'list'}),adminEvents<{events:EventRecord[]}>({action:'list'})]).then(([a,b,c])=>({places:[...a.places,...b.zones,...c.events.map(e=>({...e,kind:'event' as const}))]})),adminFunction<{configured:boolean;jobs:Job[]}>('admin-publication',{action:'status'})]);if(current!==sequence.current)return;setPlaces(catalog.places.filter(p=>p.draft_revision_id!==p.published_revision_id&&(!('archived_at'in p)||!p.archived_at||p.kind==='offleash')));setJobs(result.jobs);setConfigured(result.configured);setError('');}catch(e){if(current===sequence.current)setError(e instanceof Error?e.message:'Kon publicaties niet laden.');}finally{if(current===sequence.current)setLoading(false);}};
 useEffect(()=>{void load();return()=>{sequence.current++;};},[]);
 const active=jobs.some(job=>['requested','building'].includes(job.status));
 useEffect(()=>{if(!active)return;const timer=setInterval(()=>void load(true),15000);return()=>clearInterval(timer);},[active]);
 const publish=async()=>{setPublishing(true);setError('');setNotice('');try{const chosen=Object.fromEntries(places.filter(p=>selected.has(p.id)&&p.kind!=='event').map(p=>[p.id,p.version]));const result=await adminFunction<{error?:string}>('admin-publication',{action:'publish',places:chosen,events:Object.fromEntries(places.filter(p=>selected.has(p.id)&&p.kind==='event').map(p=>[p.id,p.version]))});setSelected(new Set());setNotice(result.error||'Publicatie gestart. De status wordt pas live zodra deze catalogus op het echte productiedomein staat.');await load();}catch(e){setError(e instanceof Error?e.message:'Publicatie kon niet gestart worden.');}finally{setPublishing(false);}};
 return <><div className="workspace-page-heading"><div><p className="workspace-eyebrow">Van concept naar je website</p><h1>Publiceren</h1><p>Kies welke opgeslagen wijzigingen aan zaken, zones en evenementen je op hondaanzee.be wilt zetten.</p></div><button className="workspace-button" disabled={loading} onClick={()=>void load()}><RefreshCw size={16}/>Vernieuwen</button></div>
 {error&&<p className="workspace-error" role="alert">{error}</p>}{notice&&<p className="workspace-success" role="status">{notice}</p>}
 {!configured&&!loading&&<p className="workspace-note">De beperkte Vercel-koppeling voor publiceren wordt nog ingesteld. Je kunt al concepten beheren.</p>}
 <section className="workspace-panel"><div className="workspace-section-heading"><div><h2>Concepten klaarzetten</h2><p className="workspace-muted">Een publicatie bouwt ook de pagina's, kaart, overzichten en sitemap.</p></div><span className="workspace-status">{places.length} concepten</span></div>{loading?<p role="status">Concepten laden…</p>:places.length?<div className="workspace-publication-list">{places.map(place=><label key={place.id}><input type="checkbox" checked={selected.has(place.id)} disabled={active||publishing} onChange={event=>setSelected(previous=>{const next=new Set(previous);event.target.checked?next.add(place.id):next.delete(place.id);return next;})}/><span><strong>{'title'in place.draft.content?place.draft.content.title:place.draft.content.name}</strong><small>{'city_slug'in place?place.city_slug:place.draft.content.cityName} · versie {place.version}{!place.published_revision_id?' · Nieuwe vermelding':''}</small></span><Link to={`/admin/${place.kind==='event'?'agenda':place.kind==='offleash'?'losloopzones':'zaken'}/${place.id}`}>Bekijken</Link></label>)}</div>:<p className="workspace-muted">Alle opgeslagen vermeldingen zijn gepubliceerd. Nieuwe aanpassingen verschijnen hier zodra je het concept opslaat.</p>}
 <div className="workspace-savebar"><p className="workspace-note">Alleen geselecteerde concepten gaan mee. Bij een mislukte build blijft je huidige website online.</p><button className="workspace-button workspace-button-primary" disabled={!configured||active||publishing||!selected.size} onClick={()=>void publish()}><UploadCloud size={18}/>{publishing?'Publicatie aanvragen…':active?'Publicatie loopt…':`${selected.size||''} ${selected.size===1?'concept':'concepten'} publiceren`}</button></div></section>
 <section className="workspace-panel"><h2>Publicatiegeschiedenis</h2>{jobs.length?<div className="workspace-publication-jobs">{jobs.map(job=><div key={job.id}>{job.status==='live'?<CheckCircle2 size={21}/>:<Clock size={21}/>}<span><strong>{statuses[job.status]}</strong><small>{new Date(job.live_at||job.created_at).toLocaleString('nl-BE')} · {job.release_id.slice(0,8)}</small>{job.error_message&&<p>{job.error_message}</p>}</span><span className="workspace-status">{job.status==='live'?'Gepubliceerd':job.status==='failed'?'Opnieuw proberen':'Bezig'}</span></div>)}</div>:<p className="workspace-muted">Nog geen publicaties vanuit het dashboard. Je bestaande website staat live.</p>}</section></>;
}
