import AdminAnalyticsNavigation from '../components/admin/AdminAnalyticsNavigation.tsx';
import {hourlySeries,type HourlyWindow} from '../utils/hourlyAnalytics.ts';
import {chartDateLabel} from '../utils/analyticsChart.ts';
import React, { useEffect, useRef, useState } from 'react';
import { RefreshCw, BarChart3, Download } from 'lucide-react';
import AdminAnalyticsChart from '../components/admin/AdminAnalyticsChart.tsx';
import AdminVercelHistory, {type VercelHistory} from '../components/admin/AdminVercelHistory.tsx';
import { adminFunction } from '../utils/adminContent.ts';
type Row={day:string;hour?:string;path:string;event:string;referrer:string;device:string;count:number};
const format=(value:number)=>new Intl.NumberFormat('nl-BE').format(value);
const labels:Record<string,string>={direct:'Rechtstreeks / onbekend',google:'Google',bing:'Bing',facebook:'Facebook',instagram:'Instagram',hondaanzee:'Binnen de website',other:'Andere websites',mobile:'Mobiel',tablet:'Tablet',desktop:'Desktop',website:'Website',route:'Route',telefoon:'Telefoon',social:'Sociale link',ticket:'Tickets / inschrijving',email:'E-mail'};
function grouped(rows:Row[],field:'path'|'referrer'|'device'|'event'){
 const counts=new Map<string,number>(); for(const row of rows)counts.set(row[field],(counts.get(row[field])||0)+Number(row.count));
 return [...counts].sort((a,b)=>b[1]-a[1]);
}
export default function AdminAnalytics(){
 const [source,setSource]=useState<'own'|'vercel'>('own'),[days,setDays]=useState(7),[result,setResult]=useState<{rows:Row[];today:string;history?:VercelHistory|null;window?:HourlyWindow}|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const sequence=useRef(0);
 const load=async(silent=false)=>{const current=++sequence.current;if(!silent)setLoading(true);setError('');try{const data=await adminFunction<{rows:Row[];today:string;history?:VercelHistory|null;window?:HourlyWindow}>('admin-analytics',days===1?{hours:24}:{days});if(current===sequence.current)setResult(data);}catch(e){if(current===sequence.current)setError(e instanceof Error?e.message:'Kon statistieken niet laden.');}finally{if(current===sequence.current)setLoading(false);}};
 useEffect(()=>{setResult(null);void load();return()=>{sequence.current++;};},[days]);
 useEffect(()=>{if(days!==1||source!=='own')return;const timer=setInterval(()=>{if(!document.hidden)void load(true);},60000);return()=>clearInterval(timer);},[days,source]);
 const rows=result?.rows||[],views=rows.filter(row=>row.event==='pageview'),actions=rows.filter(row=>row.event!=='pageview');
 const viewTotal=views.reduce((sum,row)=>sum+Number(row.count),0),actionTotal=actions.reduce((sum,row)=>sum+Number(row.count),0);
 const dailySeries=Array.from({length:days},(_,index)=>{const date=new Date(`${result?.today||new Date().toISOString().slice(0,10)}T12:00:00Z`);date.setUTCDate(date.getUTCDate()-days+1+index);const day=date.toISOString().slice(0,10);return {day,value:day<'2026-10-02'?null:views.filter(row=>row.day===day).reduce((sum,row)=>sum+Number(row.count),0),partial:day===result?.today,details:[{label:'Contactkliks',value:actions.filter(row=>row.day===day).reduce((sum,row)=>sum+Number(row.count),0)}]};});
 const series=days===1&&result?.window?hourlySeries(rows,result.window):dailySeries;
 const exportCsv=()=>{const csv=(days===1?'Uur (UTC)':'Datum')+',Pagina,Actie,Herkomst,Apparaat,Aantal\n'+rows.map(row=>[row.hour??row.day,row.path,row.event,row.referrer,row.device,row.count].map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`hondaanzee-analytics-${days===1?'24-uur':days+'-dagen'}.csv`;a.click();URL.revokeObjectURL(url);};
 const list=(title:string,items:[string,number][],links=false)=><section className="workspace-panel"><h2>{title}</h2>{items.length?<div className="workspace-analytics-list">{items.slice(0,15).map(([name,count])=><div key={name}>{links?<a href={name} target="_blank" rel="noreferrer">{name}</a>:<span>{labels[name]||name}</span>}<strong>{format(count)}</strong></div>)}</div>:<p className="workspace-muted">Nog geen gegevens in deze periode.</p>}</section>;
 return <><div className="workspace-page-heading"><div><p className="workspace-eyebrow">Je gids in cijfers</p><h1>Analytics</h1><p>Paginaweergaven en contactkliks op je openbare website.</p></div><button className="workspace-button workspace-button-primary" disabled={loading} onClick={()=>void load()}><RefreshCw size={17}/>{loading?'Laden…':'Vernieuwen'}</button></div>
 <AdminAnalyticsNavigation/>
 <div className="workspace-period" aria-label="Gegevensbron"><button className={source==='own'?'is-active':''} aria-pressed={source==='own'} onClick={()=>setSource('own')}>Eigen meting</button><button className={source==='vercel'?'is-active':''} aria-pressed={source==='vercel'} onClick={()=>setSource('vercel')}>Vercel-historiek</button></div>
 {source==='vercel'?<>{error&&<p className="workspace-error" role="alert">{error}</p>}{loading?<section className="workspace-panel" role="status">Historiek laden…</section>:<AdminVercelHistory history={result?.history||null}/>}</>:<>
 <div className="workspace-period" aria-label="Meetperiode">{[1,7,30,90,365].map(value=><button key={value} className={days===value?'is-active':''} aria-pressed={days===value} onClick={()=>setDays(value)}>{value===1?'24 uur':value===365?'12 maanden':`${value} dagen`}</button>)}</div>
 {error&&<p className="workspace-error" role="alert">{error}</p>}
 <p className="workspace-note">Eigen meting vanaf 2 oktober 2026 · Tijdzone Brussel · Vercel-historiek staat in een afzonderlijk overzicht. Contactkliks tonen interesse; ze bevestigen geen bezoek of reservering.</p>
 {days===1&&result?.window&&<p className="workspace-note">Uurmeting gestart op {new Date(result.window.startedAt).toLocaleString('nl-BE',{timeZone:'Europe/Brussels',dateStyle:'short',timeStyle:'short'})}. Eerdere uren zijn niet afzonderlijk gemeten. Het lopende en eerste gemeten uur zijn gedeeltelijk; dagtotalen blijven behouden.</p>}
 {loading?<section className="workspace-panel" role="status">Statistieken laden…</section>:result&&<>
 <div className="workspace-stats"><section className="workspace-stat"><span>Paginaweergaven</span><strong>{format(viewTotal)}</strong><small>Alle openbare pagina's</small></section><section className="workspace-stat"><span>Zaakpaginaweergaven</span><strong>{format(views.filter(row=>/\/(hotspots|diensten)\//.test(row.path)).reduce((sum,row)=>sum+Number(row.count),0))}</strong><small>Interesse in je vermeldingen</small></section><section className="workspace-stat"><span>Contactkliks</span><strong>{format(actionTotal)}</strong><small>Website, route, telefoon en social</small></section></div>
 <section className="workspace-panel"><div className="workspace-section-heading"><div><h2><BarChart3 size={20}/> Paginaweergaven doorheen de tijd</h2><p className="workspace-muted">{days===1?'Per uur · de 23 vorige uren en het lopende uur.':'Het aantal gemeten paginaweergaven per dag.'}</p></div><button className="workspace-button" onClick={exportCsv}><Download size={16}/>CSV</button></div><AdminAnalyticsChart points={series} source="Eigen meting · Brussel" label={`${format(viewTotal)} paginaweergaven in ${days===1?'24 uur':days+' dagen'}`}/>{!viewTotal&&<p className="workspace-muted">De meting staat aan. De eerste echte paginaweergaven verschijnen hier zodra bezoekers je website gebruiken.</p>}<details><summary>Cijfers per {days===1?'uur':'dag'}</summary><div className="workspace-analytics-list">{series.map(point=><div key={point.day}><span>{days===1?chartDateLabel(point):point.day}{point.partial&&days===1?' · gedeeltelijk':''}</span><strong>{point.value===null?'Nog niet gemeten':format(point.value)}</strong></div>)}</div></details></section>
 <div className="workspace-columns">{list('Populaire pagina’s',grouped(views,'path'),true)}{list('Contactacties per zaak',grouped(actions,'path'),true)}{list('Waar komen bezoekers vandaan?',grouped(views,'referrer'))}{list('Contactacties',grouped(actions,'event'))}{list('Apparaten',grouped(views,'device'))}</div>
 </>}
 <p className="workspace-note">Zonder meetcookies of bezoeker-ID. Dagtotalen worden maximaal 13 maanden bewaard; uurdetails 8 dagen. Admin, ontwikkelverkeer en bekende bots worden uitgesloten. Adblockers en privacyvoorkeuren kunnen tellingen verlagen.</p></>}</>;
}
