import {siteVisitorRows,visitorTotal,visitorSeries,visitorCsv,type VisitorReport} from '../utils/visitorAnalytics.ts';
import AdminAnalyticsNavigation from '../components/admin/AdminAnalyticsNavigation.tsx';
import {hourlySeries,type HourlyWindow} from '../utils/hourlyAnalytics.ts';
import {chartDateLabel} from '../utils/analyticsChart.ts';
import React, { useEffect, useRef, useState } from 'react';
import { RefreshCw, BarChart3, Download } from 'lucide-react';
import AdminAnalyticsChart from '../components/admin/AdminAnalyticsChart.tsx';
import AdminVercelHistory, {type VercelHistory} from '../components/admin/AdminVercelHistory.tsx';
import { adminFunction } from '../utils/adminContent.ts';
type Row={day:string;hour?:string;path:string;event:string;referrer:string;device:string;count:number};
const format=(value:number)=>new Intl.NumberFormat('nl-BE').format(value);
const labels:Record<string,string>={direct:'Rechtstreeks / onbekend',google:'Google',bing:'Bing',facebook:'Facebook',instagram:'Instagram',hondaanzee:'Binnen de website',other:'Andere websites',mobile:'Mobiel',tablet:'Tablet',desktop:'Desktop',website:'Website',route:'Route',telefoon:'Telefoon',social:'Sociale link',ticket:'Tickets / inschrijving',email:'E-mail'};
function grouped<K extends 'path'|'referrer'|'device'|'event'>(rows:(Record<K,string>&{count:number})[],field:K){
 const counts=new Map<string,number>(); for(const row of rows)counts.set(row[field],(counts.get(row[field])||0)+Number(row.count));
 return [...counts].sort((a,b)=>b[1]-a[1]);
}
export default function AdminAnalytics(){
 const [metric,setMetric]=useState<'pageviews'|'visitors'>('pageviews');
 const [source,setSource]=useState<'own'|'vercel'>('own'),[days,setDays]=useState(7),[result,setResult]=useState<{rows:Row[];today:string;history?:VercelHistory|null;window?:HourlyWindow;visitors?:VisitorReport}|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const sequence=useRef(0);
 const load=async(silent=false)=>{const current=++sequence.current;if(!silent)setLoading(true);setError('');try{const data=await adminFunction<{rows:Row[];today:string;history?:VercelHistory|null;window?:HourlyWindow;visitors?:VisitorReport}>('admin-analytics',days===1?{hours:24}:{days});if(current===sequence.current)setResult(data);}catch(e){if(current===sequence.current)setError(e instanceof Error?e.message:'Kon statistieken niet laden.');}finally{if(current===sequence.current)setLoading(false);}};
 useEffect(()=>{setResult(null);void load();return()=>{sequence.current++;};},[days]);
 useEffect(()=>{if(days!==1||source!=='own')return;const timer=setInterval(()=>{if(!document.hidden)void load(true);},60000);return()=>clearInterval(timer);},[days,source]);
 const rows=result?.rows||[],views=rows.filter(row=>row.event==='pageview'),actions=rows.filter(row=>row.event!=='pageview');
 const viewTotal=views.reduce((sum,row)=>sum+Number(row.count),0),actionTotal=actions.reduce((sum,row)=>sum+Number(row.count),0);
 const dailySeries=Array.from({length:days},(_,index)=>{const date=new Date(`${result?.today||new Date().toISOString().slice(0,10)}T12:00:00Z`);date.setUTCDate(date.getUTCDate()-days+1+index);const day=date.toISOString().slice(0,10);return {day,value:day<'2026-10-02'?null:views.filter(row=>row.day===day).reduce((sum,row)=>sum+Number(row.count),0),partial:day===result?.today,details:[{label:'Contactkliks',value:actions.filter(row=>row.day===day).reduce((sum,row)=>sum+Number(row.count),0)}]};});
 const visitorReport=result?.visitors,visitorRows=siteVisitorRows(visitorReport),visitorCount=visitorTotal(visitorReport),showVisitors=metric==='visitors';
 const selectedRows=showVisitors?visitorRows:views,selectedPages=showVisitors?(visitorReport?.rows||[]).filter(row=>row.path!=='@site'):views;
 const pageviewSeries=days===1&&result?.window?hourlySeries(rows,result.window):dailySeries;
 const series=showVisitors?visitorSeries(visitorReport,days,result?.today||new Date().toISOString().slice(0,10),result?.window):pageviewSeries;
 const total=showVisitors?visitorCount:viewTotal,metricLabel=showVisitors?(days===1?'Nieuwe bezoekers van de dag':'Geschatte bezoekers'):'Paginaweergaven';
 const exportCsv=()=>{const csv=showVisitors&&visitorReport?visitorCsv(visitorReport,days===1):(days===1?'Uur (UTC)':'Datum')+',Pagina,Actie,Herkomst,Apparaat,Aantal\n'+rows.map(row=>[row.hour??row.day,row.path,row.event,row.referrer,row.device,row.count].map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`hondaanzee-${metric}-${days===1?'24-uur':days+'-dagen'}.csv`;a.click();URL.revokeObjectURL(url);};
 const list=(title:string,items:[string,number][],links=false)=><section className="workspace-panel"><h2>{title}</h2>{items.length?<div className="workspace-analytics-list">{items.slice(0,15).map(([name,count])=><div key={name}>{links?<a href={name} target="_blank" rel="noreferrer">{name}</a>:<span>{labels[name]||name}</span>}<strong>{format(count)}</strong></div>)}</div>:<p className="workspace-muted">Nog geen gegevens in deze periode.</p>}</section>;
 return <><div className="workspace-page-heading"><div><p className="workspace-eyebrow">Je gids in cijfers</p><h1>Analytics</h1><p>Paginaweergaven, geschatte bezoekers en contactkliks op je openbare website.</p></div><button className="workspace-button workspace-button-primary" disabled={loading} onClick={()=>void load()}><RefreshCw size={17}/>{loading?'Laden…':'Vernieuwen'}</button></div>
 <AdminAnalyticsNavigation/>
 <div className="workspace-period" aria-label="Gegevensbron"><button className={source==='own'?'is-active':''} aria-pressed={source==='own'} onClick={()=>setSource('own')}>Eigen meting</button><button className={source==='vercel'?'is-active':''} aria-pressed={source==='vercel'} onClick={()=>setSource('vercel')}>Vercel-historiek</button></div>
 {source==='vercel'?<>{error&&<p className="workspace-error" role="alert">{error}</p>}{loading?<section className="workspace-panel" role="status">Historiek laden…</section>:<AdminVercelHistory history={result?.history||null}/>}</>:<>
 <div className="workspace-period" aria-label="Meetperiode">{[1,7,30,90,365].map(value=><button key={value} className={days===value?'is-active':''} aria-pressed={days===value} onClick={()=>{if(value!==days){setLoading(true);setDays(value);}}}>{value===1?'24 uur':value===365?'12 maanden':`${value} dagen`}</button>)}</div>
 <div className="workspace-period" aria-label="Meetwaarde"><button className={!showVisitors?'is-active':''} aria-pressed={!showVisitors} onClick={()=>setMetric('pageviews')}>Paginaweergaven</button><button className={showVisitors?'is-active':''} aria-pressed={showVisitors} onClick={()=>setMetric('visitors')}>Bezoekers</button></div>
 {error&&<p className="workspace-error" role="alert">{error}</p>}
 {loading?<section className="workspace-panel" role="status">Statistieken laden…</section>:result&&<>
 <div className="workspace-stats"><section className="workspace-stat"><span>Paginaweergaven</span><strong>{format(viewTotal)}</strong><small>Alle openbare pagina's</small></section><section className="workspace-stat"><span>Geschatte bezoekers</span><strong>{visitorReport?.startedAt?format(visitorCount):'—'}</strong><small>Som van dagelijks unieke schattingen</small></section><section className="workspace-stat"><span>Zaakpaginaweergaven</span><strong>{format(views.filter(row=>/\/(hotspots|diensten)\//.test(row.path)).reduce((sum,row)=>sum+Number(row.count),0))}</strong><small>Interesse in je vermeldingen</small></section><section className="workspace-stat"><span>Contactkliks</span><strong>{format(actionTotal)}</strong><small>Website, route, telefoon en social</small></section></div>
 <details className="workspace-visitor-method"><summary>Hoe worden bezoekers geteld?</summary> <p className="workspace-note">Bezoekers zijn een schatting zonder cookies: één browser/netwerkcombinatie telt per dag één keer voor de hele website. Een terugkerende bezoeker kan op een andere dag opnieuw meetellen; een periodetotaal is de som van die dagtellingen, geen uniek aantal personen over de hele periode. {visitorReport?.startedAt?`Bezoekersmeting vanaf ${new Date(visitorReport.startedAt).toLocaleString('nl-BE',{timeZone:'Europe/Brussels',dateStyle:'short',timeStyle:'short'})}; de eerste dag is gedeeltelijk.`:'De bezoekersmeting wacht op het eerste gemeten bezoek. Oudere bezoekersaantallen zijn niet beschikbaar.'} {days===1&&showVisitors?'Per uur tonen we wanneer een bezoeker die dag voor het eerst is gemeten.':''}</p> <p className="workspace-note">Eén bezoeker kan meerdere pagina’s bekijken. De bezoekersaantallen per pagina tellen daarom niet op tot het totaal van de hele website. Herkomst en apparaten tellen per dagelijks eerste websitebezoek.</p>
 <p className="workspace-note">Zonder meetcookies of blijvende bezoeker-ID. Een dagelijks wisselende hash van IP-adres en browserinformatie voorkomt dubbele dagtellingen en wordt bij de dagelijkse opschoning verwijderd. Dagtotalen worden maximaal 13 maanden bewaard; uurdetails 8 dagen. Admin, ontwikkelverkeer en bekende bots worden uitgesloten. Adblockers en privacyvoorkeuren kunnen tellingen verlagen.</p></details>
 <section className="workspace-panel"><div className="workspace-section-heading"><div><h2><BarChart3 size={20}/> {showVisitors?'Bezoekers':'Paginaweergaven'} doorheen de tijd</h2><p className="workspace-muted">{showVisitors?(days===1?'Nieuwe bezoekers van de dag per uur · elk dagelijks eerste bezoek telt één keer.':'Geschatte unieke bezoekers per dag · op een andere dag kan iemand opnieuw meetellen.'):(days===1?'Per uur · de 23 vorige uren en het lopende uur.':'Het aantal gemeten paginaweergaven per dag.')}</p></div><button className="workspace-button" disabled={!!error||(showVisitors&&!visitorReport?.startedAt)} onClick={exportCsv}><Download size={16}/>CSV</button></div><AdminAnalyticsChart points={series} source={showVisitors?"Dagelijkse bezoekersschatting · Brussel":"Eigen meting · Brussel"} metricLabel={metricLabel} label={showVisitors&&!visitorReport?.startedAt?'Bezoekersmeting wacht op het eerste gemeten bezoek':`${format(total)} ${showVisitors?'geschatte dagelijkse bezoekers':'paginaweergaven'} in ${days===1?'24 uur':days+' dagen'}`}/>{!total&&<p className="workspace-muted">De eerste gemeten bezoeken verschijnen hier zodra bezoekers je website gebruiken.</p>}<details><summary>Cijfers per {days===1?'uur':'dag'}</summary><div className="workspace-analytics-list">{series.map(point=><div key={point.day}><span>{days===1?chartDateLabel(point):point.day}{point.partial&&days===1?' · gedeeltelijk':''}</span><strong>{point.value===null?'Nog niet gemeten':format(point.value)}</strong></div>)}</div></details></section>
 <div className="workspace-columns">{list(showVisitors?'Bezoekers per pagina':'Populaire pagina’s',grouped(selectedPages,'path'),true)}{list('Contactacties per zaak',grouped(actions,'path'),true)}{list(showVisitors?'Herkomst bij eerste bezoek van de dag':'Herkomst van paginaweergaven',grouped(selectedRows,'referrer'))}{list('Contactacties',grouped(actions,'event'))}{list('Apparaten',grouped(selectedRows,'device'))}</div>
 </>}
</>}</>;
}
