import React, { useEffect, useRef, useState } from 'react';
import { RefreshCw, BarChart3, Download } from 'lucide-react';
import AdminVercelHistory, {type VercelHistory} from '../components/admin/AdminVercelHistory.tsx';
import { adminFunction } from '../utils/adminContent.ts';
type Row={day:string;path:string;event:string;referrer:string;device:string;count:number};
const format=(value:number)=>new Intl.NumberFormat('nl-BE').format(value);
const labels:Record<string,string>={direct:'Rechtstreeks / onbekend',google:'Google',bing:'Bing',facebook:'Facebook',instagram:'Instagram',hondaanzee:'Binnen de website',other:'Andere websites',mobile:'Mobiel',tablet:'Tablet',desktop:'Desktop',website:'Website',route:'Route',telefoon:'Telefoon',social:'Sociale link'};
function grouped(rows:Row[],field:'path'|'referrer'|'device'|'event'){
 const counts=new Map<string,number>(); for(const row of rows)counts.set(row[field],(counts.get(row[field])||0)+Number(row.count));
 return [...counts].sort((a,b)=>b[1]-a[1]);
}
export default function AdminAnalytics(){
 const [source,setSource]=useState<'own'|'vercel'>('own'),[days,setDays]=useState(7),[result,setResult]=useState<{rows:Row[];today:string;history?:VercelHistory|null}|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const sequence=useRef(0);
 const load=async()=>{const current=++sequence.current;setLoading(true);setError('');try{const data=await adminFunction<{rows:Row[];today:string;history?:VercelHistory|null}>('admin-analytics',{days});if(current===sequence.current)setResult(data);}catch(e){if(current===sequence.current)setError(e instanceof Error?e.message:'Kon statistieken niet laden.');}finally{if(current===sequence.current)setLoading(false);}};
 useEffect(()=>{setResult(null);void load();return()=>{sequence.current++;};},[days]);
 const rows=result?.rows||[],views=rows.filter(row=>row.event==='pageview'),actions=rows.filter(row=>row.event!=='pageview');
 const viewTotal=views.reduce((sum,row)=>sum+Number(row.count),0),actionTotal=actions.reduce((sum,row)=>sum+Number(row.count),0);
 const series=Array.from({length:days},(_,index)=>{const date=new Date(`${result?.today||new Date().toISOString().slice(0,10)}T12:00:00Z`);date.setUTCDate(date.getUTCDate()-days+1+index);const day=date.toISOString().slice(0,10);return {day,value:views.filter(row=>row.day===day).reduce((sum,row)=>sum+Number(row.count),0)};});
 const peak=Math.max(1,...series.map(point=>point.value));const x=(i:number)=>40+i*920/(days-1),y=(v:number)=>230-v/peak*190;
 const path=series.map((point,i)=>`${i?'L':'M'}${x(i)},${y(point.value)}`).join(' ');
 const exportCsv=()=>{const csv='Datum,Pagina,Actie,Herkomst,Apparaat,Aantal\n'+rows.map(row=>[row.day,row.path,row.event,row.referrer,row.device,row.count].map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`hondaanzee-analytics-${days}-dagen.csv`;a.click();URL.revokeObjectURL(url);};
 const list=(title:string,items:[string,number][],links=false)=><section className="workspace-panel"><h2>{title}</h2>{items.length?<div className="workspace-analytics-list">{items.slice(0,15).map(([name,count])=><div key={name}>{links?<a href={name} target="_blank" rel="noreferrer">{name}</a>:<span>{labels[name]||name}</span>}<strong>{format(count)}</strong></div>)}</div>:<p className="workspace-muted">Nog geen gegevens in deze periode.</p>}</section>;
 return <><div className="workspace-page-heading"><div><p className="workspace-eyebrow">Je gids in cijfers</p><h1>Analytics</h1><p>Paginaweergaven en contactkliks op je openbare website.</p></div><button className="workspace-button workspace-button-primary" disabled={loading} onClick={()=>void load()}><RefreshCw size={17}/>{loading?'Laden…':'Vernieuwen'}</button></div>
 <div className="workspace-period" aria-label="Gegevensbron"><button className={source==='own'?'is-active':''} aria-pressed={source==='own'} onClick={()=>setSource('own')}>Eigen meting</button><button className={source==='vercel'?'is-active':''} aria-pressed={source==='vercel'} onClick={()=>setSource('vercel')}>Vercel-historiek</button></div>
 {source==='vercel'?<>{error&&<p className="workspace-error" role="alert">{error}</p>}{loading?<section className="workspace-panel" role="status">Historiek laden…</section>:<AdminVercelHistory history={result?.history||null}/>}</>:<>
 <div className="workspace-period" aria-label="Meetperiode">{[7,30,90,365].map(value=><button key={value} className={days===value?'is-active':''} aria-pressed={days===value} onClick={()=>setDays(value)}>{value===365?'12 maanden':`${value} dagen`}</button>)}</div>
 {error&&<p className="workspace-error" role="alert">{error}</p>}
 <p className="workspace-note">Eigen meting vanaf 2 oktober 2026 · Tijdzone Brussel · Vercel-historiek staat in een afzonderlijk overzicht. Contactkliks tonen interesse; ze bevestigen geen bezoek of reservering.</p>
 {loading?<section className="workspace-panel" role="status">Statistieken laden…</section>:result&&<>
 <div className="workspace-stats"><section className="workspace-stat"><span>Paginaweergaven</span><strong>{format(viewTotal)}</strong><small>Alle openbare pagina's</small></section><section className="workspace-stat"><span>Zaakpaginaweergaven</span><strong>{format(views.filter(row=>/\/(hotspots|diensten)\//.test(row.path)).reduce((sum,row)=>sum+Number(row.count),0))}</strong><small>Interesse in je vermeldingen</small></section><section className="workspace-stat"><span>Contactkliks</span><strong>{format(actionTotal)}</strong><small>Website, route, telefoon en social</small></section></div>
 <section className="workspace-panel"><div className="workspace-section-heading"><div><h2><BarChart3 size={20}/> Paginaweergaven doorheen de tijd</h2><p className="workspace-muted">Het aantal gemeten paginaweergaven per dag.</p></div><button className="workspace-button" onClick={exportCsv}><Download size={16}/>CSV</button></div><svg viewBox="0 0 1000 275" className="workspace-chart" role="img" aria-label={`${format(viewTotal)} paginaweergaven in ${days} dagen`}><defs><linearGradient id="analytics-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#2346b7" stopOpacity=".18"/><stop offset="1" stopColor="#2346b7" stopOpacity="0"/></linearGradient></defs>{[0,.5,1].map(f=><g key={f}><line x1="40" x2="960" y1={y(peak*f)} y2={y(peak*f)} stroke="#e1e5ec" strokeDasharray="4 4"/><text x="0" y={y(peak*f)+5} fill="#667085" fontSize="13">{Math.round(peak*f)}</text></g>)}<path d={`${path} L960,230 L40,230 Z`} fill="url(#analytics-fill)"/><path d={path} fill="none" stroke="#2346b7" strokeWidth="3"/>{[0,Math.floor((days-1)/2),days-1].map(i=><text key={i} x={x(i)} y="263" textAnchor={i===0?'start':i===days-1?'end':'middle'} fill="#667085" fontSize="13">{series[i].day}</text>)}</svg>{!viewTotal&&<p className="workspace-muted">De meting staat aan. De eerste echte paginaweergaven verschijnen hier zodra bezoekers je website gebruiken.</p>}<details><summary>Cijfers per dag</summary><div className="workspace-analytics-list">{series.map(point=><div key={point.day}><span>{point.day}</span><strong>{format(point.value)}</strong></div>)}</div></details></section>
 <div className="workspace-columns">{list('Populaire pagina’s',grouped(views,'path'),true)}{list('Contactacties per zaak',grouped(actions,'path'),true)}{list('Waar komen bezoekers vandaan?',grouped(views,'referrer'))}{list('Contactacties',grouped(actions,'event'))}{list('Apparaten',grouped(views,'device'))}</div>
 </>}
 <p className="workspace-note">Zonder meetcookies of bezoeker-ID. Alleen dagelijkse totalen; maximaal 13 maanden bewaard. Admin, ontwikkelverkeer en bekende bots worden uitgesloten. Adblockers en privacyvoorkeuren kunnen tellingen verlagen.</p></>}</>;
}
