const fs = require('node:fs');
const path = require('node:path');
const { execSync } = require('node:child_process');
const placeData = require('./place-data.cjs');
const { getAllRoutes, PAGE_UPDATED_DATES } = placeData;
const { getPlacePageRevisions } = require('./place-page-revisions.cjs');

const ROOT_DIR = path.resolve(__dirname, '..');
const OUTPUT_PATH = path.join(ROOT_DIR, 'public', 'sitemap.xml');
const statePath = path.join(ROOT_DIR, 'data', 'placePageRevisions.json');
const previousState = fs.existsSync(statePath) ? JSON.parse(fs.readFileSync(statePath, 'utf8')) : {};
const template = ['utils/placeSEO.ts', 'utils/placeRoutes.ts', 'utils/placePresentation.ts', 'pages/PlaceDetail.tsx',
  ...fs.readdirSync(path.join(ROOT_DIR, 'components/places')).filter(file => file.endsWith('.tsx')).sort().map(file => `components/places/${file}`)]
  .map((file) => fs.readFileSync(path.join(ROOT_DIR, file), 'utf8')).join('\n');
const today = new Intl.DateTimeFormat('sv-SE', { timeZone: 'Europe/Brussels' }).format(new Date());
const placeState = getPlacePageRevisions(placeData, previousState, template, today);
const placeDates = Object.fromEntries(Object.entries(placeState).map(([route, state]) => [route, state.lastmod]));
fs.writeFileSync(statePath, `${JSON.stringify(placeState, null, 2)}\n`);
fs.writeFileSync(path.join(ROOT_DIR, 'data', 'placePageDates.ts'),
  `// AUTO-GENERATED by scripts/generate-sitemap.cjs. Keep the revision state in Git.\nexport const PLACE_PAGE_DATES: Record<string, string> = ${JSON.stringify(placeDates, null, 2)};\n`);
const previousSitemap = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, 'utf8') : '';
const previousLastmods = new Map(
  [...previousSitemap.matchAll(/<loc>https:\/\/hondaanzee\.be([^<]*)<\/loc>\s*<lastmod>([^<]+)<\/lastmod>/g)]
    .map((match) => [match[1], match[2]]),
);

const STATIC_ROUTE_FILES = {
  '/': ['pages/Home.tsx', 'components/Footer.tsx'],
  '/hotspots': ['pages/AllHotspots.tsx', 'data/hotspots.ts'],
  '/diensten': ['pages/AllServices.tsx', 'data/services.ts'],
  '/losloopzones': ['pages/AllOffLeashAreas.tsx', 'data/offLeashAreas.ts', 'cityData.ts'],
  '/kaart': ['pages/CoastalMap.tsx', 'cityData.ts'],
  '/over-ons': ['pages/About.tsx'],
  '/goed-om-te-weten': ['pages/GoedOmTeWeten.tsx'],
  '/steun-ons': ['pages/Support.tsx'],
  '/zaak-aanmelden': ['pages/ZaakAanmelden.tsx'],
  '/privacy': ['pages/Privacy.tsx'],
  '/algemene-voorwaarden': ['pages/Terms.tsx'],
  '/cookies': ['pages/Cookies.tsx'],
  '/blog': ['pages/Blog.tsx', 'data/blogs.ts'],
  '/agenda': ['pages/Agenda.tsx', 'data/events.ts'],
  '/meldpunt/vrijwilligers': ['pages/MeldpuntVrijwilligers.tsx', 'cityData.ts'],
  '/updates': ['pages/Updates.tsx', 'components/Footer.tsx'],
};

const lastmodCache = new Map();

const priorityForRoute = (route) => {
  if (route === '/') return '1.0';
  if (route.startsWith('/blog/')) return '0.8';
  if (route.startsWith('/agenda/')) return '0.8';
  if (route.includes('/hotspots/') || route.includes('/diensten/')) return '0.8';
  if (route === '/hotspots' || route === '/losloopzones') return '0.9';
  if (route === '/diensten') return '0.8';
  if (route.startsWith('/losloopzones/')) return '0.8';
  if (/^\/[^/]+$/.test(route) && route !== '/blog') return '0.9';
  return '0.7';
};

const changefreqForRoute = (route) => {
  if (route === '/') return 'daily';
  if (route === '/updates') return 'weekly';
  if (route === '/agenda' || route === '/blog') return 'weekly';
  if (route.startsWith('/agenda/')) return 'weekly';
  if (route.includes('/hotspots/') || route.includes('/diensten/')) return 'weekly';
  if (route.startsWith('/losloopzones/')) return 'weekly';
  if (/^\/[^/]+$/.test(route) && route !== '/blog') return 'weekly';
  return 'monthly';
};

const getRouteFiles = (route) => {
  if (STATIC_ROUTE_FILES[route]) {
    return STATIC_ROUTE_FILES[route];
  }

  if (route.startsWith('/hotspots/') || route.startsWith('/diensten/')) {
    return [];
  }

  if (/^\/blog\/[^/]+$/.test(route)) {
    return ['pages/BlogDetail.tsx', 'data/blogs.ts'];
  }

  if (/^\/agenda\/[^/]+$/.test(route)) {
    return ['pages/EventDetail.tsx', 'components/EventDetailContent.tsx', 'data/events.ts', 'utils/seo.ts'];
  }

  if (/^\/[^/]+\/hotspots\/[^/]+$/.test(route)) {
    return ['pages/PlaceDetail.tsx', 'data/hotspots.ts', 'utils/seo.ts', 'utils/placeRoutes.ts'];
  }

  if (/^\/[^/]+\/diensten\/[^/]+$/.test(route)) {
    return ['pages/PlaceDetail.tsx', 'data/services.ts', 'utils/seo.ts', 'utils/placeRoutes.ts'];
  }

  if (/^\/losloopzones\/[^/]+$/.test(route)) {
    return ['pages/AllOffLeashAreas.tsx', 'data/offLeashAreas.ts', 'utils/seo.ts', 'utils/offLeashRoutes.ts'];
  }

  if (/^\/[^/]+$/.test(route)) {
    return ['pages/CityPage.tsx', 'cityData.ts', 'data/hotspots.ts', 'data/services.ts'];
  }

  return [];
};

// Keep existing dates unless a page's content actually changed.
const getLastmodForRoute = (route) => {
  if (placeDates[route]) return placeDates[route];
  if (PAGE_UPDATED_DATES[route]) return PAGE_UPDATED_DATES[route];
  if (previousLastmods.has(route)) return previousLastmods.get(route);
  const files = getRouteFiles(route);
  const cacheKey = files.join('|');
  if (!lastmodCache.has(cacheKey)) {
    const date = execSync('git log -1 --format=%cs' + (files.length ? ` -- ${files.join(' ')}` : ''), {
      cwd: ROOT_DIR,
      encoding: 'utf8',
    }).trim();
    lastmodCache.set(cacheKey, date);
  }
  return lastmodCache.get(cacheKey);
};

const uniqueRoutes = [...new Set(getAllRoutes())];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${uniqueRoutes
  .map(
    (route) => `  <url>
    <loc>https://hondaanzee.be${route}</loc>
    <lastmod>${getLastmodForRoute(route)}</lastmod>
    <changefreq>${changefreqForRoute(route)}</changefreq>
    <priority>${priorityForRoute(route)}</priority>
  </url>`,
  )
  .join('\n')}
</urlset>
`;

fs.writeFileSync(OUTPUT_PATH, xml);
console.log(`Generated sitemap with ${uniqueRoutes.length} routes.`);
