import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import data from './place-data.cjs';
import html from './static-html.cjs';
import shareRoutes from '../og-routes.js';

const root = fileURLToPath(new URL('../', import.meta.url));
const shell = fs.readFileSync(path.join(root, 'dist/index.html'), 'utf8');
const routes = ['/hotspots', '/diensten', ...data.getPlaceRoutes()];
// Render the actual React template once per business, without a browser, network,
// analytics requests or an additional runtime server in production.
const vite = await createServer({
  root, configFile: false, plugins: [react()], mode: 'production',
  ssr: {
    noExternal: ['react-router-dom', 'react-router'],
    resolve: { conditions: ['module', 'import'] },
  },
  optimizeDeps: { noDiscovery: true, entries: [] },
  server: { middlewareMode: true, hmr: false, watch: null }, appType: 'custom',
});
try {
  const { renderPlaceRoute } = await vite.ssrLoadModule('/scripts/static-places.tsx');
  for (const route of routes) {
    const { body, seo } = renderPlaceRoute(route);
    if (!body.includes('<h1') || body.includes('Oeps, deze pagina is verdwaald')) throw new Error(`Incomplete page: ${route}`);
    const directory = path.join(root, 'dist', route);
    fs.mkdirSync(directory, { recursive: true });
    fs.writeFileSync(path.join(directory, 'index.html'), html.buildStaticHtml(shell, body, seo));
    shareRoutes[route] = { title: seo.title, description: seo.description, image: seo.ogImage || 'https://hondaanzee.be/og-imagefinal.webp', imageAlt: seo.title };
  }
  fs.writeFileSync(path.join(root, 'og-routes.js'), `// AUTO-GENERATED by generate-og-data.cjs and render-places.mjs\nexport default ${JSON.stringify(shareRoutes, null, 2)};\n`);
  console.log(`Static HTML ready: ${data.HOTSPOTS.length} hotspots + ${data.SERVICES.length} services + 2 complete directories.`);
} finally {
  await vite.close();
}
