import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import data from './place-data.cjs';
import html from './static-html.cjs';
import shareRoutes from '../og-routes.js';

const root = fileURLToPath(new URL('../', import.meta.url));
const shell = fs.readFileSync(path.join(root, 'dist/index.html'), 'utf8');
// Preserve an empty SPA shell for routes whose data is loaded at runtime.
const runtimeShell = shell
  .replace(/<link\b[^>]*rel="(?:canonical|alternate)"[^>]*>/gi, '')
  .replace(/<meta\b[^>]*(?:name="(?:title|description|keywords|twitter:[^"]+)"|property="og:[^"]+")[^>]*>/gi, '')
  .replace(/<div id="hero-prerender"[^>]*>[\s\S]*?<\/div>/, '')
  .replace(/<link\b[^>]*rel="preload"[^>]*as="image"[^>]*href="\/lexi(?:-mobile)?\.webp"[^>]*>/gi, '')
  .replace(/<title>[\s\S]*?<\/title>/, '<title>HondAanZee.be</title>');
fs.writeFileSync(path.join(root, 'dist/spa.html'), runtimeShell);
fs.writeFileSync(path.join(root, 'dist/private.html'), runtimeShell.replace(/<meta name="robots"[^>]*>/, '<meta name="robots" content="noindex, nofollow">'));
const businessRoutes = new Set(['/hotspots', '/diensten', ...data.getPlaceRoutes()]);
const routes = [...new Set(data.getAllRoutes())];
// Render every public React page without a browser, network,
// analytics requests or an additional runtime server in production.
const vite = await createServer({
  root, configFile: false, plugins: [react()], mode: 'production',
  resolve: { alias: [{ find: /^leaflet$/, replacement: path.join(root, 'scripts/static-leaflet.ts') }] },
  ssr: {
    noExternal: ['react-router-dom', 'react-router'],
    resolve: { conditions: ['module', 'import'] },
  },
  optimizeDeps: { noDiscovery: true, entries: [] },
  server: { middlewareMode: true, hmr: false, watch: null }, appType: 'custom',
});
try {
  const { renderPlaceRoute } = await vite.ssrLoadModule('/scripts/static-places.tsx');
  const { renderPublicRoute } = await vite.ssrLoadModule('/scripts/static-pages.tsx');
  for (const route of routes) {
    const { body, seo } = businessRoutes.has(route) ? renderPlaceRoute(route) : renderPublicRoute(route);
    if (!body.includes('<h1') || body.includes('Oeps, deze pagina is verdwaald')) throw new Error(`Incomplete page: ${route}`);
    const directory = route === '/' ? path.join(root, 'dist') : path.join(root, 'dist', route);
    fs.mkdirSync(directory, { recursive: true });
    fs.writeFileSync(path.join(directory, 'index.html'), html.buildStaticHtml(shell, body, seo));
    shareRoutes[route] = { title: seo.title, description: seo.description, image: seo.ogImage || 'https://hondaanzee.be/og-imagefinal.webp', imageAlt: seo.title };
  }
  const notFound = renderPublicRoute('/404.html');
  fs.writeFileSync(path.join(root, 'dist/404.html'), html.buildStaticHtml(shell, notFound.body, notFound.seo));
  const { verifyPublicPages } = await import('./verify-public-pages.cjs');
  verifyPublicPages();
  fs.writeFileSync(path.join(root, 'og-routes.js'), `// AUTO-GENERATED by generate-og-data.cjs and render-places.mjs\nexport default ${JSON.stringify(shareRoutes, null, 2)};\n`);
  console.log(`Static HTML ready for all ${routes.length} public URLs: ${data.HOTSPOTS.length} hotspots + ${data.SERVICES.length} services + 2 complete directories.`);
} finally {
  await vite.close();
}
